set_property IOSTANDARD DIFF_HSTL_I [get_ports sys_clk_clk_n]
set_property PACKAGE_PIN AB2 [get_ports sys_clk_clk_p]
set_property IOSTANDARD DIFF_HSTL_I [get_ports sys_clk_clk_p]
set_property PACKAGE_PIN L23 [get_ports sys_reset]
set_property IOSTANDARD LVCMOS25 [get_ports sys_reset]
set_property PACKAGE_PIN N17 [get_ports uart_txd]
set_property IOSTANDARD LVCMOS25 [get_ports uart_txd]
set_property IOSTANDARD LVCMOS25 [get_ports uart_rxd]
set_property PACKAGE_PIN D19 [get_ports uart_rxd]

set_property PACKAGE_PIN N16 [get_ports {gpio_trig_tri_o[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports {gpio_trig_tri_o[0]}]
set_property PACKAGE_PIN G20 [get_ports {gpio_led_tri_o[0]}]
set_property PACKAGE_PIN L19 [get_ports {gpio_led_tri_o[1]}]
set_property PACKAGE_PIN K18 [get_ports {gpio_led_tri_o[2]}]
set_property PACKAGE_PIN H19 [get_ports {gpio_led_tri_o[3]}]
set_property PACKAGE_PIN K15 [get_ports {gpio_led_tri_o[4]}]
set_property PACKAGE_PIN P16 [get_ports {gpio_led_tri_o[5]}]
set_property PACKAGE_PIN T19 [get_ports {gpio_led_tri_o[6]}]
set_property PACKAGE_PIN T18 [get_ports {gpio_led_tri_o[7]}]

set_property PACKAGE_PIN H12 [get_ports {gpio_led_tri_o[8]}]
set_property PACKAGE_PIN H11 [get_ports {gpio_led_tri_o[9]}]
set_property IOSTANDARD LVCMOS25 [get_ports {gpio_led_tri_o[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports {gpio_led_tri_o[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports {gpio_led_tri_o[2]}]
set_property IOSTANDARD LVCMOS25 [get_ports {gpio_led_tri_o[3]}]
set_property IOSTANDARD LVCMOS25 [get_ports {gpio_led_tri_o[4]}]
set_property IOSTANDARD LVCMOS25 [get_ports {gpio_led_tri_o[5]}]
set_property IOSTANDARD LVCMOS25 [get_ports {gpio_led_tri_o[6]}]
set_property IOSTANDARD LVCMOS25 [get_ports {gpio_led_tri_o[7]}]
set_property IOSTANDARD LVCMOS25 [get_ports {gpio_led_tri_o[8]}]
set_property IOSTANDARD LVCMOS25 [get_ports {gpio_led_tri_o[9]}]
set_property SLEW FAST [get_ports {gpio_trig_tri_o[0]}]



set_property SLEW SLOW [get_ports {gpio_led_tri_o[9]}]
set_property SLEW SLOW [get_ports {gpio_led_tri_o[8]}]
set_property SLEW SLOW [get_ports {gpio_led_tri_o[7]}]
set_property SLEW SLOW [get_ports {gpio_led_tri_o[6]}]
set_property SLEW SLOW [get_ports {gpio_led_tri_o[5]}]
set_property SLEW SLOW [get_ports {gpio_led_tri_o[4]}]
set_property SLEW SLOW [get_ports {gpio_led_tri_o[3]}]
set_property SLEW SLOW [get_ports {gpio_led_tri_o[2]}]
set_property SLEW SLOW [get_ports {gpio_led_tri_o[1]}]
set_property SLEW SLOW [get_ports {gpio_led_tri_o[0]}]
