#*****************************************************************************************
# Vivado (TM) v2019.1 (64-bit)
#
# scarv-soc-project.tcl: Tcl script for re-creating project 'scarv-soc'
#
# Generated by Vivado on Wed Oct 30 11:19:31 GMT 2019
# IP Build 2548770 on Fri May 24 18:01:18 MDT 2019
#
# This file contains the Vivado Tcl commands for re-creating the project to the state*
# when this script was generated. In order to re-create the project, please source this
# file in the Vivado Tcl Shell.
#
# * Note that the runs in the created project will be configured the same way as the
#   original project, however they will not be launched automatically. To regenerate the
#   run results please launch the synthesis/implementation runs as needed.
#
#*****************************************************************************************
# NOTE: In order to use this script for source control purposes, please make sure that the
#       following files are added to the source control system:-
#
# 1. This project restoration tcl script (scarv-soc-project.tcl) that was generated.
#
# 2. The following source(s) files that were local or imported into the original project.
#    (Please see the '$orig_proj_dir' and '$origin_dir' variable setting below at the start of the script)
#
#    "$::env(SOC_HOME)/work/vivado/scarv-soc.srcs/sources_1/bd/system_top/hdl/system_top_wrapper.v"
#    "$::env(SOC_HOME)/work/vivado/tb_top_behav.wcfg"
#
# 3. The following remote source files that were added to the original project:-
#
#    "$::env(SOC_HOME)/extern/scarv-cpu/external/xcrypto-rtl/rtl/b_bop/b_bop.v"
#    "$::env(SOC_HOME)/extern/scarv-cpu/external/xcrypto-rtl/rtl/b_lut/b_lut.v"
#    "$::env(SOC_HOME)/extern/scarv-cpu/rtl/core/frv_common.vh"
#    "$::env(SOC_HOME)/extern/scarv-cpu/rtl/core/frv_alu.v"
#    "$::env(SOC_HOME)/extern/scarv-cpu/rtl/core/frv_asi.v"
#    "$::env(SOC_HOME)/extern/scarv-cpu/rtl/core/frv_bitwise.v"
#    "$::env(SOC_HOME)/extern/scarv-cpu/rtl/core/frv_core.v"
#    "$::env(SOC_HOME)/extern/scarv-cpu/rtl/core/frv_core_fetch_buffer.v"
#    "$::env(SOC_HOME)/extern/scarv-cpu/rtl/core/frv_counters.v"
#    "$::env(SOC_HOME)/extern/scarv-cpu/rtl/core/frv_csrs.v"
#    "$::env(SOC_HOME)/extern/scarv-cpu/rtl/core/frv_gprs.v"
#    "$::env(SOC_HOME)/extern/scarv-cpu/rtl/core/frv_interrupts.v"
#    "$::env(SOC_HOME)/extern/scarv-cpu/rtl/core/frv_leak.v"
#    "$::env(SOC_HOME)/extern/scarv-cpu/rtl/core/frv_lsu.v"
#    "$::env(SOC_HOME)/extern/scarv-cpu/rtl/core/frv_pipeline.v"
#    "$::env(SOC_HOME)/extern/scarv-cpu/rtl/core/frv_pipeline_decode.vh"
#    "$::env(SOC_HOME)/extern/scarv-cpu/rtl/core/frv_pipeline_decode.v"
#    "$::env(SOC_HOME)/extern/scarv-cpu/rtl/core/frv_pipeline_execute.v"
#    "$::env(SOC_HOME)/extern/scarv-cpu/rtl/core/frv_pipeline_fetch.v"
#    "$::env(SOC_HOME)/extern/scarv-cpu/rtl/core/frv_pipeline_memory.v"
#    "$::env(SOC_HOME)/extern/scarv-cpu/rtl/core/frv_pipeline_register.v"
#    "$::env(SOC_HOME)/extern/scarv-cpu/rtl/core/frv_pipeline_writeback.v"
#    "$::env(SOC_HOME)/extern/scarv-cpu/rtl/core/frv_rngif.v"
#    "$::env(SOC_HOME)/rtl/ic/ic_addr_decode.v"
#    "$::env(SOC_HOME)/rtl/ic/ic_cpu_bus_axi_bridge.v"
#    "$::env(SOC_HOME)/rtl/ic/ic_cpu_bus_bram_bridge.v"
#    "$::env(SOC_HOME)/rtl/ic/ic_error_rsp_stub.v"
#    "$::env(SOC_HOME)/rtl/ic/ic_rsp_router.v"
#    "$::env(SOC_HOME)/rtl/ic/ic_rsp_tracker.v"
#    "$::env(SOC_HOME)/rtl/ic/ic_top.v"
#    "$::env(SOC_HOME)/extern/scarv-cpu/external/xcrypto-rtl/rtl/p_addsub/p_addsub.v"
#    "$::env(SOC_HOME)/extern/scarv-cpu/external/xcrypto-rtl/rtl/p_shfrot/p_shfrot.v"
#    "$::env(SOC_HOME)/rtl/mem/scarv_soc_bram_dual_synth_xilinx_xc7k.v"
#    "$::env(SOC_HOME)/extern/scarv-cpu/external/xcrypto-rtl/rtl/xc_aesmix/xc_aesmix.v"
#    "$::env(SOC_HOME)/extern/scarv-cpu/external/xcrypto-rtl/rtl/xc_aessub/xc_aessub.v"
#    "$::env(SOC_HOME)/extern/scarv-cpu/external/xcrypto-rtl/rtl/xc_aessub/xc_aessub_sbox.v"
#    "$::env(SOC_HOME)/extern/scarv-cpu/external/xcrypto-rtl/rtl/xc_malu/xc_malu.v"
#    "$::env(SOC_HOME)/extern/scarv-cpu/external/xcrypto-rtl/rtl/xc_malu/xc_malu_divrem.v"
#    "$::env(SOC_HOME)/extern/scarv-cpu/external/xcrypto-rtl/rtl/xc_malu/xc_malu_long.v"
#    "$::env(SOC_HOME)/extern/scarv-cpu/external/xcrypto-rtl/rtl/xc_malu/xc_malu_mul.v"
#    "$::env(SOC_HOME)/extern/scarv-cpu/external/xcrypto-rtl/rtl/xc_malu/xc_malu_muldivrem.v"
#    "$::env(SOC_HOME)/extern/scarv-cpu/external/xcrypto-rtl/rtl/xc_malu/xc_malu_pmul.v"
#    "$::env(SOC_HOME)/extern/scarv-cpu/external/xcrypto-rtl/rtl/xc_sha256/xc_sha256.v"
#    "$::env(SOC_HOME)/extern/scarv-cpu/external/xcrypto-rtl/rtl/xc_sha3/xc_sha3.v"
#    "$::env(SOC_HOME)/rtl/soc/scarv_soc.v"
#    "$::env(SOC_HOME)/flow/xilinx/constraints-xc7k.xdc"
#    "$::env(SOC_HOME)/flow/xilinx/tb_top.v"
#
#*****************************************************************************************

# Set the reference directory for source file relative paths (by default the value is script directory path)
set origin_dir "."

# Use origin directory path location variable, if specified in the tcl shell
if { [info exists ::origin_dir_loc] } {
  set origin_dir $::origin_dir_loc
}

# Set the project name
set _xil_proj_name_ "scarv-soc"

# Use project name variable, if specified in the tcl shell
if { [info exists ::user_project_name] } {
  set _xil_proj_name_ $::user_project_name
}

variable script_file
set script_file "scarv-soc-project.tcl"

# Help information for this script
proc print_help {} {
  variable script_file
  puts "\nDescription:"
  puts "Recreate a Vivado project from this script. The created project will be"
  puts "functionally equivalent to the original project for which this script was"
  puts "generated. The script contains commands for creating a project, filesets,"
  puts "runs, adding/importing sources and setting properties on various objects.\n"
  puts "Syntax:"
  puts "$script_file"
  puts "$script_file -tclargs \[--origin_dir <path>\]"
  puts "$script_file -tclargs \[--project_name <name>\]"
  puts "$script_file -tclargs \[--help\]\n"
  puts "Usage:"
  puts "Name                   Description"
  puts "-------------------------------------------------------------------------"
  puts "\[--origin_dir <path>\]  Determine source file paths wrt this path. Default"
  puts "                       origin_dir path value is \".\", otherwise, the value"
  puts "                       that was set with the \"-paths_relative_to\" switch"
  puts "                       when this script was generated.\n"
  puts "\[--project_name <name>\] Create project with the specified name. Default"
  puts "                       name is the name of the project from where this"
  puts "                       script was generated.\n"
  puts "\[--help\]               Print help information for this script"
  puts "-------------------------------------------------------------------------\n"
  exit 0
}

if { $::argc > 0 } {
  for {set i 0} {$i < $::argc} {incr i} {
    set option [string trim [lindex $::argv $i]]
    switch -regexp -- $option {
      "--origin_dir"   { incr i; set origin_dir [lindex $::argv $i] }
      "--project_name" { incr i; set _xil_proj_name_ [lindex $::argv $i] }
      "--help"         { print_help }
      default {
        if { [regexp {^-} $option] } {
          puts "ERROR: Unknown option '$option' specified, please type '$script_file -tclargs --help' for usage info.\n"
          return 1
        }
      }
    }
  }
}

# Set the directory path for the original project from where this script was exported
set orig_proj_dir "[file normalize "$::env(SOC_HOME)/work/vivado"]"

# Create project
create_project ${_xil_proj_name_} ./${_xil_proj_name_} -part xc7k160tfbg676-3

# Set the directory path for the new project
set proj_dir [get_property directory [current_project]]

# Set project properties
set obj [current_project]
set_property -name "default_lib" -value "xil_defaultlib" -objects $obj
set_property -name "dsa.accelerator_binary_content" -value "bitstream" -objects $obj
set_property -name "dsa.accelerator_binary_format" -value "xclbin2" -objects $obj
set_property -name "dsa.description" -value "Vivado generated DSA" -objects $obj
set_property -name "dsa.dr_bd_base_address" -value "0" -objects $obj
set_property -name "dsa.emu_dir" -value "emu" -objects $obj
set_property -name "dsa.flash_interface_type" -value "bpix16" -objects $obj
set_property -name "dsa.flash_offset_address" -value "0" -objects $obj
set_property -name "dsa.flash_size" -value "1024" -objects $obj
set_property -name "dsa.host_architecture" -value "x86_64" -objects $obj
set_property -name "dsa.host_interface" -value "pcie" -objects $obj
set_property -name "dsa.num_compute_units" -value "60" -objects $obj
set_property -name "dsa.platform_state" -value "pre_synth" -objects $obj
set_property -name "dsa.vendor" -value "xilinx" -objects $obj
set_property -name "dsa.version" -value "0.0" -objects $obj
set_property -name "enable_vhdl_2008" -value "1" -objects $obj
set_property -name "ip_cache_permissions" -value "read write" -objects $obj
set_property -name "ip_output_repo" -value "$proj_dir/${_xil_proj_name_}.cache/ip" -objects $obj
set_property -name "mem.enable_memory_map_generation" -value "1" -objects $obj
set_property -name "part" -value "xc7k160tfbg676-3" -objects $obj
set_property -name "sim.central_dir" -value "$proj_dir/${_xil_proj_name_}.ip_user_files" -objects $obj
set_property -name "sim.ip.auto_export_scripts" -value "1" -objects $obj
set_property -name "simulator_language" -value "Mixed" -objects $obj
set_property -name "webtalk.activehdl_export_sim" -value "17" -objects $obj
set_property -name "webtalk.ies_export_sim" -value "17" -objects $obj
set_property -name "webtalk.modelsim_export_sim" -value "17" -objects $obj
set_property -name "webtalk.questa_export_sim" -value "17" -objects $obj
set_property -name "webtalk.riviera_export_sim" -value "17" -objects $obj
set_property -name "webtalk.vcs_export_sim" -value "17" -objects $obj
set_property -name "webtalk.xcelium_export_sim" -value "16" -objects $obj
set_property -name "webtalk.xsim_export_sim" -value "17" -objects $obj
set_property -name "webtalk.xsim_launch_sim" -value "31" -objects $obj
set_property -name "xpm_libraries" -value "XPM_CDC XPM_MEMORY" -objects $obj

# Create 'sources_1' fileset (if not found)
if {[string equal [get_filesets -quiet sources_1] ""]} {
  create_fileset -srcset sources_1
}

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 [file normalize "$::env(SOC_HOME)/extern/scarv-cpu/external/xcrypto-rtl/rtl/b_bop/b_bop.v"] \
 [file normalize "$::env(SOC_HOME)/extern/scarv-cpu/external/xcrypto-rtl/rtl/b_lut/b_lut.v"] \
 [file normalize "$::env(SOC_HOME)/extern/scarv-cpu/rtl/core/frv_common.vh"] \
 [file normalize "$::env(SOC_HOME)/extern/scarv-cpu/rtl/core/frv_alu.v"] \
 [file normalize "$::env(SOC_HOME)/extern/scarv-cpu/rtl/core/frv_asi.v"] \
 [file normalize "$::env(SOC_HOME)/extern/scarv-cpu/rtl/core/frv_bitwise.v"] \
 [file normalize "$::env(SOC_HOME)/extern/scarv-cpu/rtl/core/frv_core.v"] \
 [file normalize "$::env(SOC_HOME)/extern/scarv-cpu/rtl/core/frv_core_fetch_buffer.v"] \
 [file normalize "$::env(SOC_HOME)/extern/scarv-cpu/rtl/core/frv_counters.v"] \
 [file normalize "$::env(SOC_HOME)/extern/scarv-cpu/rtl/core/frv_csrs.v"] \
 [file normalize "$::env(SOC_HOME)/extern/scarv-cpu/rtl/core/frv_gprs.v"] \
 [file normalize "$::env(SOC_HOME)/extern/scarv-cpu/rtl/core/frv_interrupts.v"] \
 [file normalize "$::env(SOC_HOME)/extern/scarv-cpu/rtl/core/frv_leak.v"] \
 [file normalize "$::env(SOC_HOME)/extern/scarv-cpu/rtl/core/frv_lsu.v"] \
 [file normalize "$::env(SOC_HOME)/extern/scarv-cpu/rtl/core/frv_pipeline.v"] \
 [file normalize "$::env(SOC_HOME)/extern/scarv-cpu/rtl/core/frv_pipeline_decode.vh"] \
 [file normalize "$::env(SOC_HOME)/extern/scarv-cpu/rtl/core/frv_pipeline_decode.v"] \
 [file normalize "$::env(SOC_HOME)/extern/scarv-cpu/rtl/core/frv_pipeline_execute.v"] \
 [file normalize "$::env(SOC_HOME)/extern/scarv-cpu/rtl/core/frv_pipeline_fetch.v"] \
 [file normalize "$::env(SOC_HOME)/extern/scarv-cpu/rtl/core/frv_pipeline_memory.v"] \
 [file normalize "$::env(SOC_HOME)/extern/scarv-cpu/rtl/core/frv_pipeline_register.v"] \
 [file normalize "$::env(SOC_HOME)/extern/scarv-cpu/rtl/core/frv_pipeline_writeback.v"] \
 [file normalize "$::env(SOC_HOME)/extern/scarv-cpu/rtl/core/frv_rngif.v"] \
 [file normalize "$::env(SOC_HOME)/rtl/ic/ic_addr_decode.v"] \
 [file normalize "$::env(SOC_HOME)/rtl/ic/ic_cpu_bus_axi_bridge.v"] \
 [file normalize "$::env(SOC_HOME)/rtl/ic/ic_cpu_bus_bram_bridge.v"] \
 [file normalize "$::env(SOC_HOME)/rtl/ic/ic_error_rsp_stub.v"] \
 [file normalize "$::env(SOC_HOME)/rtl/ic/ic_rsp_router.v"] \
 [file normalize "$::env(SOC_HOME)/rtl/ic/ic_rsp_tracker.v"] \
 [file normalize "$::env(SOC_HOME)/rtl/ic/ic_top.v"] \
 [file normalize "$::env(SOC_HOME)/extern/scarv-cpu/external/xcrypto-rtl/rtl/p_addsub/p_addsub.v"] \
 [file normalize "$::env(SOC_HOME)/extern/scarv-cpu/external/xcrypto-rtl/rtl/p_shfrot/p_shfrot.v"] \
 [file normalize "$::env(SOC_HOME)/rtl/mem/scarv_soc_bram_dual_synth_xilinx_xc7k.v"] \
 [file normalize "$::env(SOC_HOME)/extern/scarv-cpu/external/xcrypto-rtl/rtl/xc_aesmix/xc_aesmix.v"] \
 [file normalize "$::env(SOC_HOME)/extern/scarv-cpu/external/xcrypto-rtl/rtl/xc_aessub/xc_aessub.v"] \
 [file normalize "$::env(SOC_HOME)/extern/scarv-cpu/external/xcrypto-rtl/rtl/xc_aessub/xc_aessub_sbox.v"] \
 [file normalize "$::env(SOC_HOME)/extern/scarv-cpu/external/xcrypto-rtl/rtl/xc_malu/xc_malu.v"] \
 [file normalize "$::env(SOC_HOME)/extern/scarv-cpu/external/xcrypto-rtl/rtl/xc_malu/xc_malu_divrem.v"] \
 [file normalize "$::env(SOC_HOME)/extern/scarv-cpu/external/xcrypto-rtl/rtl/xc_malu/xc_malu_long.v"] \
 [file normalize "$::env(SOC_HOME)/extern/scarv-cpu/external/xcrypto-rtl/rtl/xc_malu/xc_malu_mul.v"] \
 [file normalize "$::env(SOC_HOME)/extern/scarv-cpu/external/xcrypto-rtl/rtl/xc_malu/xc_malu_muldivrem.v"] \
 [file normalize "$::env(SOC_HOME)/extern/scarv-cpu/external/xcrypto-rtl/rtl/xc_malu/xc_malu_pmul.v"] \
 [file normalize "$::env(SOC_HOME)/extern/scarv-cpu/external/xcrypto-rtl/rtl/xc_sha256/xc_sha256.v"] \
 [file normalize "$::env(SOC_HOME)/extern/scarv-cpu/external/xcrypto-rtl/rtl/xc_sha3/xc_sha3.v"] \
 [file normalize "$::env(SOC_HOME)/rtl/soc/scarv_soc.v"] \
]
add_files -norecurse -fileset $obj $files

# Import local files from the original project
set files [list \
 [file normalize "$::env(SOC_HOME)/rtl/xilinx/system_top_wrapper.v" ]\
]
set imported_files [import_files -fileset sources_1 $files]

# Set 'sources_1' fileset file properties for remote files
set file "$::env(SOC_HOME)/extern/scarv-cpu/rtl/core/frv_common.vh"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "Verilog Header" -objects $file_obj

set file "$::env(SOC_HOME)/extern/scarv-cpu/rtl/core/frv_pipeline_decode.vh"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "Verilog Header" -objects $file_obj


# Set 'sources_1' fileset file properties for local files
# None

# Set 'sources_1' fileset properties
set obj [get_filesets sources_1]
set_property -name "top" -value "system_top_wrapper" -objects $obj
set_property -name "top_auto_set" -value "0" -objects $obj

# Create 'constrs_1' fileset (if not found)
if {[string equal [get_filesets -quiet constrs_1] ""]} {
  create_fileset -constrset constrs_1
}

# Set 'constrs_1' fileset object
set obj [get_filesets constrs_1]

# Add/Import constrs file and set constrs file properties
set file "[file normalize "$::env(SOC_HOME)/flow/xilinx/constraints-xc7k.xdc"]"
set file_added [add_files -norecurse -fileset $obj [list $file]]
set file "$::env(SOC_HOME)/flow/xilinx/constraints-xc7k.xdc"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets constrs_1] [list "*$file"]]
set_property -name "file_type" -value "XDC" -objects $file_obj

# Set 'constrs_1' fileset properties
set obj [get_filesets constrs_1]
set_property -name "target_part" -value "xc7k160tfbg676-3" -objects $obj

# Create 'sim_1' fileset (if not found)
if {[string equal [get_filesets -quiet sim_1] ""]} {
  create_fileset -simset sim_1
}

# Set 'sim_1' fileset object
set obj [get_filesets sim_1]
set files [list \
 [file normalize "$::env(SOC_HOME)/verif/xilinx/tb_top.v"] \
]
add_files -norecurse -fileset $obj $files

# Import local files from the original project
set files [list \
 [file normalize "$::env(SOC_HOME)/flow/xilinx/tb_top_behav.wcfg" ]\
]
set imported_files [import_files -fileset sim_1 $files]

# Set 'sim_1' fileset file properties for remote files
# None

# Set 'sim_1' fileset file properties for local files
# None

# Set 'sim_1' fileset properties
set obj [get_filesets sim_1]
set_property -name "top" -value "tb_top" -objects $obj
set_property -name "top_auto_set" -value "0" -objects $obj
set_property -name "top_lib" -value "xil_defaultlib" -objects $obj

# Set 'utils_1' fileset object
set obj [get_filesets utils_1]
# Empty (no sources present)

# Set 'utils_1' fileset properties
set obj [get_filesets utils_1]


# Adding sources referenced in BDs, if not already added
if { [get_files b_bop.v] == "" } {
  import_files -quiet -fileset sources_1 $::env(SOC_HOME)/extern/scarv-cpu/external/xcrypto-rtl/rtl/b_bop/b_bop.v
}
if { [get_files b_lut.v] == "" } {
  import_files -quiet -fileset sources_1 $::env(SOC_HOME)/extern/scarv-cpu/external/xcrypto-rtl/rtl/b_lut/b_lut.v
}
if { [get_files frv_common.vh] == "" } {
  import_files -quiet -fileset sources_1 $::env(SOC_HOME)/extern/scarv-cpu/rtl/core/frv_common.vh
}
if { [get_files frv_alu.v] == "" } {
  import_files -quiet -fileset sources_1 $::env(SOC_HOME)/extern/scarv-cpu/rtl/core/frv_alu.v
}
if { [get_files frv_asi.v] == "" } {
  import_files -quiet -fileset sources_1 $::env(SOC_HOME)/extern/scarv-cpu/rtl/core/frv_asi.v
}
if { [get_files frv_bitwise.v] == "" } {
  import_files -quiet -fileset sources_1 $::env(SOC_HOME)/extern/scarv-cpu/rtl/core/frv_bitwise.v
}
if { [get_files frv_core.v] == "" } {
  import_files -quiet -fileset sources_1 $::env(SOC_HOME)/extern/scarv-cpu/rtl/core/frv_core.v
}
if { [get_files frv_core_fetch_buffer.v] == "" } {
  import_files -quiet -fileset sources_1 $::env(SOC_HOME)/extern/scarv-cpu/rtl/core/frv_core_fetch_buffer.v
}
if { [get_files frv_counters.v] == "" } {
  import_files -quiet -fileset sources_1 $::env(SOC_HOME)/extern/scarv-cpu/rtl/core/frv_counters.v
}
if { [get_files frv_csrs.v] == "" } {
  import_files -quiet -fileset sources_1 $::env(SOC_HOME)/extern/scarv-cpu/rtl/core/frv_csrs.v
}
if { [get_files frv_gprs.v] == "" } {
  import_files -quiet -fileset sources_1 $::env(SOC_HOME)/extern/scarv-cpu/rtl/core/frv_gprs.v
}
if { [get_files frv_interrupts.v] == "" } {
  import_files -quiet -fileset sources_1 $::env(SOC_HOME)/extern/scarv-cpu/rtl/core/frv_interrupts.v
}
if { [get_files frv_leak.v] == "" } {
  import_files -quiet -fileset sources_1 $::env(SOC_HOME)/extern/scarv-cpu/rtl/core/frv_leak.v
}
if { [get_files frv_lsu.v] == "" } {
  import_files -quiet -fileset sources_1 $::env(SOC_HOME)/extern/scarv-cpu/rtl/core/frv_lsu.v
}
if { [get_files frv_pipeline.v] == "" } {
  import_files -quiet -fileset sources_1 $::env(SOC_HOME)/extern/scarv-cpu/rtl/core/frv_pipeline.v
}
if { [get_files frv_pipeline_decode.vh] == "" } {
  import_files -quiet -fileset sources_1 $::env(SOC_HOME)/extern/scarv-cpu/rtl/core/frv_pipeline_decode.vh
}
if { [get_files frv_pipeline_decode.v] == "" } {
  import_files -quiet -fileset sources_1 $::env(SOC_HOME)/extern/scarv-cpu/rtl/core/frv_pipeline_decode.v
}
if { [get_files frv_pipeline_execute.v] == "" } {
  import_files -quiet -fileset sources_1 $::env(SOC_HOME)/extern/scarv-cpu/rtl/core/frv_pipeline_execute.v
}
if { [get_files frv_pipeline_fetch.v] == "" } {
  import_files -quiet -fileset sources_1 $::env(SOC_HOME)/extern/scarv-cpu/rtl/core/frv_pipeline_fetch.v
}
if { [get_files frv_pipeline_memory.v] == "" } {
  import_files -quiet -fileset sources_1 $::env(SOC_HOME)/extern/scarv-cpu/rtl/core/frv_pipeline_memory.v
}
if { [get_files frv_pipeline_register.v] == "" } {
  import_files -quiet -fileset sources_1 $::env(SOC_HOME)/extern/scarv-cpu/rtl/core/frv_pipeline_register.v
}
if { [get_files frv_pipeline_writeback.v] == "" } {
  import_files -quiet -fileset sources_1 $::env(SOC_HOME)/extern/scarv-cpu/rtl/core/frv_pipeline_writeback.v
}
if { [get_files frv_rngif.v] == "" } {
  import_files -quiet -fileset sources_1 $::env(SOC_HOME)/extern/scarv-cpu/rtl/core/frv_rngif.v
}
if { [get_files ic_addr_decode.v] == "" } {
  import_files -quiet -fileset sources_1 $::env(SOC_HOME)/rtl/ic/ic_addr_decode.v
}
if { [get_files ic_cpu_bus_axi_bridge.v] == "" } {
  import_files -quiet -fileset sources_1 $::env(SOC_HOME)/rtl/ic/ic_cpu_bus_axi_bridge.v
}
if { [get_files ic_cpu_bus_bram_bridge.v] == "" } {
  import_files -quiet -fileset sources_1 $::env(SOC_HOME)/rtl/ic/ic_cpu_bus_bram_bridge.v
}
if { [get_files ic_error_rsp_stub.v] == "" } {
  import_files -quiet -fileset sources_1 $::env(SOC_HOME)/rtl/ic/ic_error_rsp_stub.v
}
if { [get_files ic_rsp_router.v] == "" } {
  import_files -quiet -fileset sources_1 $::env(SOC_HOME)/rtl/ic/ic_rsp_router.v
}
if { [get_files ic_rsp_tracker.v] == "" } {
  import_files -quiet -fileset sources_1 $::env(SOC_HOME)/rtl/ic/ic_rsp_tracker.v
}
if { [get_files ic_top.v] == "" } {
  import_files -quiet -fileset sources_1 $::env(SOC_HOME)/rtl/ic/ic_top.v
}
if { [get_files p_addsub.v] == "" } {
  import_files -quiet -fileset sources_1 $::env(SOC_HOME)/extern/scarv-cpu/external/xcrypto-rtl/rtl/p_addsub/p_addsub.v
}
if { [get_files p_shfrot.v] == "" } {
  import_files -quiet -fileset sources_1 $::env(SOC_HOME)/extern/scarv-cpu/external/xcrypto-rtl/rtl/p_shfrot/p_shfrot.v
}
if { [get_files scarv_soc_bram_dual_synth_xilinx_xc7k.v] == "" } {
  import_files -quiet -fileset sources_1 $::env(SOC_HOME)/rtl/mem/scarv_soc_bram_dual_synth_xilinx_xc7k.v
}
if { [get_files xc_aesmix.v] == "" } {
  import_files -quiet -fileset sources_1 $::env(SOC_HOME)/extern/scarv-cpu/external/xcrypto-rtl/rtl/xc_aesmix/xc_aesmix.v
}
if { [get_files xc_aessub.v] == "" } {
  import_files -quiet -fileset sources_1 $::env(SOC_HOME)/extern/scarv-cpu/external/xcrypto-rtl/rtl/xc_aessub/xc_aessub.v
}
if { [get_files xc_aessub_sbox.v] == "" } {
  import_files -quiet -fileset sources_1 $::env(SOC_HOME)/extern/scarv-cpu/external/xcrypto-rtl/rtl/xc_aessub/xc_aessub_sbox.v
}
if { [get_files xc_malu.v] == "" } {
  import_files -quiet -fileset sources_1 $::env(SOC_HOME)/extern/scarv-cpu/external/xcrypto-rtl/rtl/xc_malu/xc_malu.v
}
if { [get_files xc_malu_divrem.v] == "" } {
  import_files -quiet -fileset sources_1 $::env(SOC_HOME)/extern/scarv-cpu/external/xcrypto-rtl/rtl/xc_malu/xc_malu_divrem.v
}
if { [get_files xc_malu_long.v] == "" } {
  import_files -quiet -fileset sources_1 $::env(SOC_HOME)/extern/scarv-cpu/external/xcrypto-rtl/rtl/xc_malu/xc_malu_long.v
}
if { [get_files xc_malu_mul.v] == "" } {
  import_files -quiet -fileset sources_1 $::env(SOC_HOME)/extern/scarv-cpu/external/xcrypto-rtl/rtl/xc_malu/xc_malu_mul.v
}
if { [get_files xc_malu_muldivrem.v] == "" } {
  import_files -quiet -fileset sources_1 $::env(SOC_HOME)/extern/scarv-cpu/external/xcrypto-rtl/rtl/xc_malu/xc_malu_muldivrem.v
}
if { [get_files xc_malu_pmul.v] == "" } {
  import_files -quiet -fileset sources_1 $::env(SOC_HOME)/extern/scarv-cpu/external/xcrypto-rtl/rtl/xc_malu/xc_malu_pmul.v
}
if { [get_files xc_sha256.v] == "" } {
  import_files -quiet -fileset sources_1 $::env(SOC_HOME)/extern/scarv-cpu/external/xcrypto-rtl/rtl/xc_sha256/xc_sha256.v
}
if { [get_files xc_sha3.v] == "" } {
  import_files -quiet -fileset sources_1 $::env(SOC_HOME)/extern/scarv-cpu/external/xcrypto-rtl/rtl/xc_sha3/xc_sha3.v
}
if { [get_files scarv_soc.v] == "" } {
  import_files -quiet -fileset sources_1 $::env(SOC_HOME)/rtl/soc/scarv_soc.v
}


# Proc to create BD system_top
proc cr_bd_system_top { parentCell } {
# The design that will be created by this Tcl proc contains the following 
# module references:
# scarv_soc



  # CHANGE DESIGN NAME HERE
  set design_name system_top

  common::send_msg_id "BD_TCL-003" "INFO" "Currently there is no design <$design_name> in project, so creating one..."

  create_bd_design $design_name

  set bCheckIPsPassed 1
  ##################################################################
  # CHECK IPs
  ##################################################################
  set bCheckIPs 1
  if { $bCheckIPs == 1 } {
     set list_check_ips "\ 
  xilinx.com:ip:xlconstant:1.1\
  xilinx.com:ip:clk_wiz:6.0\
  xilinx.com:ip:axi_gpio:2.0\
  xilinx.com:ip:proc_sys_reset:5.0\
  xilinx.com:ip:axi_uartlite:2.0\
  "

   set list_ips_missing ""
   common::send_msg_id "BD_TCL-006" "INFO" "Checking if the following IPs exist in the project's IP catalog: $list_check_ips ."

   foreach ip_vlnv $list_check_ips {
      set ip_obj [get_ipdefs -all $ip_vlnv]
      if { $ip_obj eq "" } {
         lappend list_ips_missing $ip_vlnv
      }
   }

   if { $list_ips_missing ne "" } {
      catch {common::send_msg_id "BD_TCL-115" "ERROR" "The following IPs are not found in the IP Catalog:\n  $list_ips_missing\n\nResolution: Please add the repository containing the IP(s) to the project." }
      set bCheckIPsPassed 0
   }

  }

  ##################################################################
  # CHECK Modules
  ##################################################################
  set bCheckModules 1
  if { $bCheckModules == 1 } {
     set list_check_mods "\ 
  scarv_soc\
  "

   set list_mods_missing ""
   common::send_msg_id "BD_TCL-006" "INFO" "Checking if the following modules exist in the project's sources: $list_check_mods ."

   foreach mod_vlnv $list_check_mods {
      if { [can_resolve_reference $mod_vlnv] == 0 } {
         lappend list_mods_missing $mod_vlnv
      }
   }

   if { $list_mods_missing ne "" } {
      catch {common::send_msg_id "BD_TCL-115" "ERROR" "The following module(s) are not found in the project: $list_mods_missing" }
      common::send_msg_id "BD_TCL-008" "INFO" "Please add source files for the missing module(s) above."
      set bCheckIPsPassed 0
   }
}

  if { $bCheckIPsPassed != 1 } {
    common::send_msg_id "BD_TCL-1003" "WARNING" "Will not continue with creation of design due to the error(s) above."
    return 3
  }

  variable script_folder

  if { $parentCell eq "" } {
     set parentCell [get_bd_cells /]
  }

  # Get object for parentCell
  set parentObj [get_bd_cells $parentCell]
  if { $parentObj == "" } {
     catch {common::send_msg_id "BD_TCL-100" "ERROR" "Unable to find parent cell <$parentCell>!"}
     return
  }

  # Make sure parentObj is hier blk
  set parentType [get_property TYPE $parentObj]
  if { $parentType ne "hier" } {
     catch {common::send_msg_id "BD_TCL-101" "ERROR" "Parent <$parentObj> has TYPE = <$parentType>. Expected to be <hier>."}
     return
  }

  # Save current instance; Restore later
  set oldCurInst [current_bd_instance .]

  # Set parent object as current
  current_bd_instance $parentObj


  # Create interface ports
  set gpio_led [ create_bd_intf_port -mode Master -vlnv xilinx.com:interface:gpio_rtl:1.0 gpio_led ]

  set gpio_trig [ create_bd_intf_port -mode Master -vlnv xilinx.com:interface:gpio_rtl:1.0 gpio_trig ]

  set sys_clk [ create_bd_intf_port -mode Slave -vlnv xilinx.com:interface:diff_clock_rtl:1.0 sys_clk ]
  set_property -dict [ list \
   CONFIG.FREQ_HZ {200000000} \
   ] $sys_clk

  set uart [ create_bd_intf_port -mode Master -vlnv xilinx.com:interface:uart_rtl:1.0 uart ]


  # Create ports
  set sys_reset [ create_bd_port -dir I -type rst sys_reset ]
  set_property -dict [ list \
   CONFIG.POLARITY {ACTIVE_HIGH} \
 ] $sys_reset

  # Create instance: AXI_IC, and set properties
  set AXI_IC [ create_bd_cell -type ip -vlnv xilinx.com:ip:axi_interconnect:2.1 AXI_IC ]

  # Create instance: CONST_0, and set properties
  set CONST_0 [ create_bd_cell -type ip -vlnv xilinx.com:ip:xlconstant:1.1 CONST_0 ]
  set_property -dict [ list \
   CONFIG.CONST_VAL {0} \
 ] $CONST_0

  # Create instance: SOC_HOME, and set properties
  set block_name scarv_soc
  set block_cell_name SOC_HOME
  if { [catch {set SOC_HOME [create_bd_cell -type module -reference $block_name $block_cell_name] } errmsg] } {
     catch {common::send_msg_id "BD_TCL-105" "ERROR" "Unable to add referenced block <$block_name>. Please add the files for ${block_name}'s definition into the project."}
     return 1
   } elseif { $SOC_HOME eq "" } {
     catch {common::send_msg_id "BD_TCL-106" "ERROR" "Unable to referenced block <$block_name>. Please add the files for ${block_name}'s definition into the project."}
     return 1
   }
    set_property -dict [ list \
   CONFIG.BRAM_ROM_MEMH_FILE $::env(SOC_WORK)/fsbl/fsbl-vivado.hex \
 ] $SOC_HOME

  # Create instance: SYS_CLK, and set properties
  set SYS_CLK [ create_bd_cell -type ip -vlnv xilinx.com:ip:clk_wiz:6.0 SYS_CLK ]
  set_property -dict [ list \
   CONFIG.CLKIN1_JITTER_PS {50.0} \
   CONFIG.CLKOUT1_JITTER {112.316} \
   CONFIG.CLKOUT1_PHASE_ERROR {89.971} \
   CONFIG.CLK_OUT1_PORT {clk_100} \
   CONFIG.MMCM_CLKFBOUT_MULT_F {5.000} \
   CONFIG.MMCM_CLKIN1_PERIOD {5.000} \
   CONFIG.MMCM_CLKIN2_PERIOD {10.0} \
   CONFIG.PRIM_IN_FREQ {200.000} \
   CONFIG.PRIM_SOURCE {Differential_clock_capable_pin} \
 ] $SYS_CLK

  # Create instance: SYS_GPIO, and set properties
  set SYS_GPIO [ create_bd_cell -type ip -vlnv xilinx.com:ip:axi_gpio:2.0 SYS_GPIO ]
  set_property -dict [ list \
   CONFIG.C_ALL_OUTPUTS {1} \
   CONFIG.C_ALL_OUTPUTS_2 {1} \
   CONFIG.C_DOUT_DEFAULT_2 {0x00000010} \
   CONFIG.C_GPIO2_WIDTH {10} \
   CONFIG.C_GPIO_WIDTH {1} \
   CONFIG.C_IS_DUAL {1} \
 ] $SYS_GPIO

  # Create instance: SYS_RESET, and set properties
  set SYS_RESET [ create_bd_cell -type ip -vlnv xilinx.com:ip:proc_sys_reset:5.0 SYS_RESET ]

  # Create instance: SYS_UART0, and set properties
  set SYS_UART0 [ create_bd_cell -type ip -vlnv xilinx.com:ip:axi_uartlite:2.0 SYS_UART0 ]
  set_property -dict [ list \
   CONFIG.C_BAUDRATE {128000} \
 ] $SYS_UART0

  # Create interface connections
  connect_bd_intf_net -intf_net SOC_HOME_m0 [get_bd_intf_pins AXI_IC/S00_AXI] [get_bd_intf_pins SOC_HOME/m0]
  connect_bd_intf_net -intf_net SYS_GPIO_GPIO [get_bd_intf_ports gpio_trig] [get_bd_intf_pins SYS_GPIO/GPIO]
  connect_bd_intf_net -intf_net SYS_GPIO_GPIO2 [get_bd_intf_ports gpio_led] [get_bd_intf_pins SYS_GPIO/GPIO2]
  connect_bd_intf_net -intf_net SYS_UART0_UART [get_bd_intf_ports uart] [get_bd_intf_pins SYS_UART0/UART]
  connect_bd_intf_net -intf_net axi_interconnect_0_M00_AXI [get_bd_intf_pins AXI_IC/M00_AXI] [get_bd_intf_pins SYS_UART0/S_AXI]
  connect_bd_intf_net -intf_net axi_interconnect_0_M01_AXI [get_bd_intf_pins AXI_IC/M01_AXI] [get_bd_intf_pins SYS_GPIO/S_AXI]
  connect_bd_intf_net -intf_net diff_clock_rtl_0_1 [get_bd_intf_ports sys_clk] [get_bd_intf_pins SYS_CLK/CLK_IN1_D]

  # Create port connections
  connect_bd_net -net CLK_clk_out1 [get_bd_pins AXI_IC/ACLK] [get_bd_pins AXI_IC/M00_ACLK] [get_bd_pins AXI_IC/M01_ACLK] [get_bd_pins AXI_IC/S00_ACLK] [get_bd_pins SOC_HOME/g_clk] [get_bd_pins SYS_CLK/clk_100] [get_bd_pins SYS_GPIO/s_axi_aclk] [get_bd_pins SYS_RESET/slowest_sync_clk] [get_bd_pins SYS_UART0/s_axi_aclk]
  connect_bd_net -net proc_sys_reset_0_peripheral_aresetn [get_bd_pins AXI_IC/ARESETN] [get_bd_pins AXI_IC/M00_ARESETN] [get_bd_pins AXI_IC/M01_ARESETN] [get_bd_pins AXI_IC/S00_ARESETN] [get_bd_pins SOC_HOME/g_resetn] [get_bd_pins SYS_GPIO/s_axi_aresetn] [get_bd_pins SYS_RESET/peripheral_aresetn] [get_bd_pins SYS_UART0/s_axi_aresetn]
  connect_bd_net -net reset_rtl_0_1 [get_bd_ports sys_reset] [get_bd_pins SYS_RESET/ext_reset_in]
  connect_bd_net -net xlconstant_0_dout [get_bd_pins CONST_0/dout] [get_bd_pins SOC_HOME/cpu_int_external] [get_bd_pins SOC_HOME/cpu_int_software] [get_bd_pins SYS_CLK/reset]

  # Create address segments
  create_bd_addr_seg -range 0x00001000 -offset 0x40002000 [get_bd_addr_spaces SOC_HOME/m0] [get_bd_addr_segs SYS_GPIO/S_AXI/Reg] SEG_SYS_GPIO_Reg
  create_bd_addr_seg -range 0x00001000 -offset 0x40001000 [get_bd_addr_spaces SOC_HOME/m0] [get_bd_addr_segs SYS_UART0/S_AXI/Reg] SEG_SYS_UART0_Reg

  # Perform GUI Layout
  regenerate_bd_layout -layout_string {
   "ExpandedHierarchyInLayout":"",
   "guistr":"# # String gsaved with Nlview 7.0.19  2019-03-26 bk=1.5019 VDI=41 GEI=35 GUI=JA:9.0 TLS
#  -string -flagsOSRD
preplace port sys_clk -pg 1 -lvl 0 -x 0 -y 70 -defaultsOSRD
preplace port gpio_trig -pg 1 -lvl 7 -x 1630 -y 210 -defaultsOSRD
preplace port uart -pg 1 -lvl 7 -x 1630 -y 70 -defaultsOSRD
preplace port gpio_led -pg 1 -lvl 7 -x 1630 -y 230 -defaultsOSRD
preplace port sys_reset -pg 1 -lvl 0 -x 0 -y 190 -defaultsOSRD
preplace inst SYS_CLK -pg 1 -lvl 2 -x 290 -y 80 -defaultsOSRD
preplace inst SYS_RESET -pg 1 -lvl 3 -x 580 -y 210 -defaultsOSRD
preplace inst AXI_IC -pg 1 -lvl 5 -x 1200 -y 190 -defaultsOSRD
preplace inst SYS_GPIO -pg 1 -lvl 6 -x 1490 -y 220 -defaultsOSRD
preplace inst SYS_UART0 -pg 1 -lvl 6 -x 1490 -y 80 -defaultsOSRD
preplace inst CONST_0 -pg 1 -lvl 1 -x 100 -y 130 -defaultsOSRD
preplace inst SOC_HOME -pg 1 -lvl 4 -x 910 -y 110 -defaultsOSRD
preplace netloc reset_rtl_0_1 1 0 3 NJ 190 NJ 190 NJ
preplace netloc CLK_clk_out1 1 2 4 400 80 770 200 1050 50 1360
preplace netloc proc_sys_reset_0_peripheral_aresetn 1 3 3 780 210 1040 330 1370
preplace netloc xlconstant_0_dout 1 1 3 180 10 NJ 10 760
preplace netloc axi_interconnect_0_M01_AXI 1 5 1 N 200
preplace netloc SYS_UART0_UART 1 6 1 NJ 70
preplace netloc SOC_HOME_m0 1 4 1 N 110
preplace netloc SYS_GPIO_GPIO 1 6 1 NJ 210
preplace netloc diff_clock_rtl_0_1 1 0 2 NJ 70 NJ
preplace netloc axi_interconnect_0_M00_AXI 1 5 1 1350 60n
preplace netloc SYS_GPIO_GPIO2 1 6 1 NJ 230
levelinfo -pg 1 0 100 290 580 910 1200 1490 1630
pagesize -pg 1 -db -bbox -sgen -120 0 1750 340
"
}

  # Restore current instance
  current_bd_instance $oldCurInst

  validate_bd_design
  save_bd_design
  close_bd_design $design_name 
}
# End of cr_bd_system_top()
cr_bd_system_top ""
set_property REGISTERED_WITH_MANAGER "1" [get_files system_top.bd ] 
set_property SYNTH_CHECKPOINT_MODE "Hierarchical" [get_files system_top.bd ] 

# Create 'synth_1' run (if not found)
if {[string equal [get_runs -quiet synth_1] ""]} {
    create_run -name synth_1 -part xc7k160tfbg676-3 -flow {Vivado Synthesis 2019} -strategy "Vivado Synthesis Defaults" -report_strategy {No Reports} -constrset constrs_1
} else {
  set_property strategy "Vivado Synthesis Defaults" [get_runs synth_1]
  set_property flow "Vivado Synthesis 2019" [get_runs synth_1]
}
set obj [get_runs synth_1]
set_property set_report_strategy_name 1 $obj
set_property report_strategy {Vivado Synthesis Default Reports} $obj
set_property set_report_strategy_name 0 $obj
# Create 'synth_1_synth_report_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs synth_1] synth_1_synth_report_utilization_0] "" ] } {
  create_report_config -report_name synth_1_synth_report_utilization_0 -report_type report_utilization:1.0 -steps synth_design -runs synth_1
}
set obj [get_report_configs -of_objects [get_runs synth_1] synth_1_synth_report_utilization_0]
if { $obj != "" } {

}
set obj [get_runs synth_1]
set_property -name "part" -value "xc7k160tfbg676-3" -objects $obj
set_property -name "strategy" -value "Vivado Synthesis Defaults" -objects $obj

# set the current synth run
current_run -synthesis [get_runs synth_1]

# Create 'impl_1' run (if not found)
if {[string equal [get_runs -quiet impl_1] ""]} {
    create_run -name impl_1 -part xc7k160tfbg676-3 -flow {Vivado Implementation 2019} -strategy "Vivado Implementation Defaults" -report_strategy {No Reports} -constrset constrs_1 -parent_run synth_1
} else {
  set_property strategy "Vivado Implementation Defaults" [get_runs impl_1]
  set_property flow "Vivado Implementation 2019" [get_runs impl_1]
}
set obj [get_runs impl_1]
set_property set_report_strategy_name 1 $obj
set_property report_strategy {Vivado Implementation Default Reports} $obj
set_property set_report_strategy_name 0 $obj
# Create 'impl_1_init_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_init_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_init_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps init_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_init_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj

}
# Create 'impl_1_opt_report_drc_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_drc_0] "" ] } {
  create_report_config -report_name impl_1_opt_report_drc_0 -report_type report_drc:1.0 -steps opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_drc_0]
if { $obj != "" } {

}
# Create 'impl_1_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj

}
# Create 'impl_1_power_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_power_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_power_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps power_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_power_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj

}
# Create 'impl_1_place_report_io_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_io_0] "" ] } {
  create_report_config -report_name impl_1_place_report_io_0 -report_type report_io:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_io_0]
if { $obj != "" } {

}
# Create 'impl_1_place_report_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_utilization_0] "" ] } {
  create_report_config -report_name impl_1_place_report_utilization_0 -report_type report_utilization:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_utilization_0]
if { $obj != "" } {

}
# Create 'impl_1_place_report_control_sets_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_control_sets_0] "" ] } {
  create_report_config -report_name impl_1_place_report_control_sets_0 -report_type report_control_sets:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_control_sets_0]
if { $obj != "" } {
set_property -name "options.verbose" -value "1" -objects $obj

}
# Create 'impl_1_place_report_incremental_reuse_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_0] "" ] } {
  create_report_config -report_name impl_1_place_report_incremental_reuse_0 -report_type report_incremental_reuse:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'impl_1_place_report_incremental_reuse_1' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_1] "" ] } {
  create_report_config -report_name impl_1_place_report_incremental_reuse_1 -report_type report_incremental_reuse:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_1]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'impl_1_place_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_place_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj

}
# Create 'impl_1_post_place_power_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_post_place_power_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_post_place_power_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps post_place_power_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_post_place_power_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj

}
# Create 'impl_1_phys_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_phys_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_phys_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps phys_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_phys_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj

}
# Create 'impl_1_route_report_drc_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_drc_0] "" ] } {
  create_report_config -report_name impl_1_route_report_drc_0 -report_type report_drc:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_drc_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_methodology_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_methodology_0] "" ] } {
  create_report_config -report_name impl_1_route_report_methodology_0 -report_type report_methodology:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_methodology_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_power_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_power_0] "" ] } {
  create_report_config -report_name impl_1_route_report_power_0 -report_type report_power:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_power_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_route_status_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_route_status_0] "" ] } {
  create_report_config -report_name impl_1_route_report_route_status_0 -report_type report_route_status:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_route_status_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_route_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_timing_summary_0]
if { $obj != "" } {
set_property -name "options.max_paths" -value "10" -objects $obj

}
# Create 'impl_1_route_report_incremental_reuse_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_incremental_reuse_0] "" ] } {
  create_report_config -report_name impl_1_route_report_incremental_reuse_0 -report_type report_incremental_reuse:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_incremental_reuse_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_clock_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_clock_utilization_0] "" ] } {
  create_report_config -report_name impl_1_route_report_clock_utilization_0 -report_type report_clock_utilization:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_clock_utilization_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_bus_skew_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_bus_skew_0] "" ] } {
  create_report_config -report_name impl_1_route_report_bus_skew_0 -report_type report_bus_skew:1.1 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_bus_skew_0]
if { $obj != "" } {
set_property -name "options.warn_on_violation" -value "1" -objects $obj

}
# Create 'impl_1_post_route_phys_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_post_route_phys_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps post_route_phys_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.warn_on_violation" -value "1" -objects $obj

}
# Create 'impl_1_post_route_phys_opt_report_bus_skew_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_bus_skew_0] "" ] } {
  create_report_config -report_name impl_1_post_route_phys_opt_report_bus_skew_0 -report_type report_bus_skew:1.1 -steps post_route_phys_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_bus_skew_0]
if { $obj != "" } {
set_property -name "options.warn_on_violation" -value "1" -objects $obj

}
set obj [get_runs impl_1]
set_property -name "part" -value "xc7k160tfbg676-3" -objects $obj
set_property -name "strategy" -value "Vivado Implementation Defaults" -objects $obj
set_property -name "steps.write_bitstream.args.readback_file" -value "0" -objects $obj
set_property -name "steps.write_bitstream.args.verbose" -value "0" -objects $obj

# set the current impl run
current_run -implementation [get_runs impl_1]

puts "INFO: Project created:${_xil_proj_name_}"
# Create 'drc_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "drc_1" ] ] ""]} {
create_dashboard_gadget -name {drc_1} -type drc
}
set obj [get_dashboard_gadgets [ list "drc_1" ] ]
set_property -name "reports" -value "impl_1#impl_1_route_report_drc_0" -objects $obj

# Create 'methodology_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "methodology_1" ] ] ""]} {
create_dashboard_gadget -name {methodology_1} -type methodology
}
set obj [get_dashboard_gadgets [ list "methodology_1" ] ]
set_property -name "reports" -value "impl_1#impl_1_route_report_methodology_0" -objects $obj

# Create 'power_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "power_1" ] ] ""]} {
create_dashboard_gadget -name {power_1} -type power
}
set obj [get_dashboard_gadgets [ list "power_1" ] ]
set_property -name "reports" -value "impl_1#impl_1_route_report_power_0" -objects $obj

# Create 'timing_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "timing_1" ] ] ""]} {
create_dashboard_gadget -name {timing_1} -type timing
}
set obj [get_dashboard_gadgets [ list "timing_1" ] ]
set_property -name "reports" -value "impl_1#impl_1_route_report_timing_summary_0" -objects $obj

# Create 'utilization_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "utilization_1" ] ] ""]} {
create_dashboard_gadget -name {utilization_1} -type utilization
}
set obj [get_dashboard_gadgets [ list "utilization_1" ] ]
set_property -name "reports" -value "synth_1#synth_1_synth_report_utilization_0" -objects $obj
set_property -name "run.step" -value "synth_design" -objects $obj
set_property -name "run.type" -value "synthesis" -objects $obj

# Create 'utilization_2' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "utilization_2" ] ] ""]} {
create_dashboard_gadget -name {utilization_2} -type utilization
}
set obj [get_dashboard_gadgets [ list "utilization_2" ] ]
set_property -name "reports" -value "impl_1#impl_1_place_report_utilization_0" -objects $obj

move_dashboard_gadget -name {utilization_1} -row 0 -col 0
move_dashboard_gadget -name {power_1} -row 1 -col 0
move_dashboard_gadget -name {drc_1} -row 2 -col 0
move_dashboard_gadget -name {timing_1} -row 0 -col 1
move_dashboard_gadget -name {utilization_2} -row 1 -col 1
move_dashboard_gadget -name {methodology_1} -row 2 -col 1

exit

