#*****************************************************************************************
# Vivado (TM) v2019.2 (64-bit)
#
# scarv-soc-project-cw305.tcl: Tcl script for re-creating project 'scarv-soc-masking-ise-cw305'
#
# Generated by Vivado on Fri Oct 22 15:15:32 BST 2021
# IP Build 2700528 on Thu Nov  7 00:09:20 MST 2019
#
# This file contains the Vivado Tcl commands for re-creating the project to the state*
# when this script was generated. In order to re-create the project, please source this
# file in the Vivado Tcl Shell.
#
# * Note that the runs in the created project will be configured the same way as the
#   original project, however they will not be launched automatically. To regenerate the
#   run results please launch the synthesis/implementation runs as needed.
#
#*****************************************************************************************
# NOTE: In order to use this script for source control purposes, please make sure that the
#       following files are added to the source control system:-
#
# 1. This project restoration tcl script (scarv-soc-project-cw305.tcl) that was generated.
#
# 2. The following source(s) files that were local or imported into the original project.
#    (Please see the '$orig_proj_dir' and '$origin_dir' variable setting below at the start of the script)
#
#    "/home/work/scarv/scarv-soc-masking-ise/work/vivado/scarv-soc-masking-ise-cw305/scarv-soc-masking-ise-cw305.srcs/sources_1/bd/system_top_wrapper/hdl/system_top_wrapper_wrapper.v"
#    "/home/work/scarv/scarv-soc-masking-ise/work/vivado/scarv-soc-masking-ise-cw305/scarv-soc-masking-ise-cw305.srcs/sim_1/imports/xilinx/tb_top_behav.wcfg"
#
# 3. The following remote source files that were added to the original project:-
#
#    "/home/work/scarv/scarv-soc-masking-ise/extern/scarv-cpu/external/xcrypto/rtl/b_bop/b_bop.v"
#    "/home/work/scarv/scarv-soc-masking-ise/extern/scarv-cpu/external/xcrypto/rtl/b_lut/b_lut.v"
#    "/home/work/scarv/scarv-soc-masking-ise/extern/scarv-cpu/rtl/core/frv_common.vh"
#    "/home/work/scarv/scarv-soc-masking-ise/extern/scarv-cpu/rtl/core/frv_alu.v"
#    "/home/work/scarv/scarv-soc-masking-ise/extern/scarv-cpu/rtl/core/frv_asi.v"
#    "/home/work/scarv/scarv-soc-masking-ise/extern/scarv-cpu/rtl/core/frv_bitwise.v"
#    "/home/work/scarv/scarv-soc-masking-ise/extern/scarv-cpu/rtl/core/frv_core.v"
#    "/home/work/scarv/scarv-soc-masking-ise/extern/scarv-cpu/rtl/core/frv_core_fetch_buffer.v"
#    "/home/work/scarv/scarv-soc-masking-ise/extern/scarv-cpu/rtl/core/frv_counters.v"
#    "/home/work/scarv/scarv-soc-masking-ise/extern/scarv-cpu/rtl/core/frv_csrs.v"
#    "/home/work/scarv/scarv-soc-masking-ise/extern/scarv-cpu/rtl/core/frv_gf256_aff.v"
#    "/home/work/scarv/scarv-soc-masking-ise/extern/scarv-cpu/rtl/core/frv_gf256_mul.v"
#    "/home/work/scarv/scarv-soc-masking-ise/extern/scarv-cpu/rtl/core/frv_gprs.v"
#    "/home/work/scarv/scarv-soc-masking-ise/extern/scarv-cpu/rtl/core/frv_interrupts.v"
#    "/home/work/scarv/scarv-soc-masking-ise/extern/scarv-cpu/rtl/core/frv_leak.v"
#    "/home/work/scarv/scarv-soc-masking-ise/extern/scarv-cpu/rtl/core/frv_lfsr32.v"
#    "/home/work/scarv/scarv-soc-masking-ise/extern/scarv-cpu/rtl/core/frv_lsu.v"
#    "/home/work/scarv/scarv-soc-masking-ise/extern/scarv-cpu/rtl/core/frv_masked_alu.v"
#    "/home/work/scarv/scarv-soc-masking-ise/extern/scarv-cpu/rtl/core/frv_masked_arith.v"
#    "/home/work/scarv/scarv-soc-masking-ise/extern/scarv-cpu/rtl/core/frv_masked_barith.v"
#    "/home/work/scarv/scarv-soc-masking-ise/extern/scarv-cpu/rtl/core/frv_masked_bitwise.v"
#    "/home/work/scarv/scarv-soc-masking-ise/extern/scarv-cpu/rtl/core/frv_masked_faff.v"
#    "/home/work/scarv/scarv-soc-masking-ise/extern/scarv-cpu/rtl/core/frv_masked_fmul.v"
#    "/home/work/scarv/scarv-soc-masking-ise/extern/scarv-cpu/rtl/core/frv_masked_shfrot.v"
#    "/home/work/scarv/scarv-soc-masking-ise/extern/scarv-cpu/rtl/core/frv_masked_shuffle.v"
#    "/home/work/scarv/scarv-soc-masking-ise/extern/scarv-cpu/rtl/core/frv_pipeline.v"
#    "/home/work/scarv/scarv-soc-masking-ise/extern/scarv-cpu/rtl/core/frv_pipeline_decode.vh"
#    "/home/work/scarv/scarv-soc-masking-ise/extern/scarv-cpu/rtl/core/frv_pipeline_decode.v"
#    "/home/work/scarv/scarv-soc-masking-ise/extern/scarv-cpu/rtl/core/frv_pipeline_execute.v"
#    "/home/work/scarv/scarv-soc-masking-ise/extern/scarv-cpu/rtl/core/frv_pipeline_fetch.v"
#    "/home/work/scarv/scarv-soc-masking-ise/extern/scarv-cpu/rtl/core/frv_pipeline_memory.v"
#    "/home/work/scarv/scarv-soc-masking-ise/extern/scarv-cpu/rtl/core/frv_pipeline_register.v"
#    "/home/work/scarv/scarv-soc-masking-ise/extern/scarv-cpu/rtl/core/frv_pipeline_writeback.v"
#    "/home/work/scarv/scarv-soc-masking-ise/extern/scarv-cpu/rtl/core/frv_rngif.v"
#    "/home/work/scarv/scarv-soc-masking-ise/extern/scarv-cpu/rtl/core/frv_trng.v"
#    "/home/work/scarv/scarv-soc-masking-ise/rtl/ic/ic_addr_decode.v"
#    "/home/work/scarv/scarv-soc-masking-ise/rtl/ic/ic_cpu_bus_axi_bridge.v"
#    "/home/work/scarv/scarv-soc-masking-ise/rtl/ic/ic_cpu_bus_bram_bridge.v"
#    "/home/work/scarv/scarv-soc-masking-ise/rtl/ic/ic_error_rsp_stub.v"
#    "/home/work/scarv/scarv-soc-masking-ise/rtl/ic/ic_rsp_tracker.v"
#    "/home/work/scarv/scarv-soc-masking-ise/rtl/ic/ic_top.v"
#    "/home/work/scarv/scarv-soc-masking-ise/extern/scarv-cpu/external/xcrypto/rtl/p_addsub/p_addsub.v"
#    "/home/work/scarv/scarv-soc-masking-ise/extern/scarv-cpu/external/xcrypto/rtl/p_shfrot/p_shfrot.v"
#    "/home/work/scarv/scarv-soc-masking-ise/rtl/rng/scarv_rng_lfsr.v"
#    "/home/work/scarv/scarv-soc-masking-ise/rtl/rng/scarv_rng_top.v"
#    "/home/work/scarv/scarv-soc-masking-ise/rtl/mem/scarv_soc_bram_dual_synth_xilinx_xc7k.v"
#    "/home/work/scarv/scarv-soc-masking-ise/extern/scarv-cpu/external/xcrypto/rtl/xc_aesmix/xc_aesmix.v"
#    "/home/work/scarv/scarv-soc-masking-ise/extern/scarv-cpu/external/xcrypto/rtl/xc_aessub/xc_aessub.v"
#    "/home/work/scarv/scarv-soc-masking-ise/extern/scarv-cpu/external/xcrypto/rtl/xc_aessub/xc_aessub_sbox.v"
#    "/home/work/scarv/scarv-soc-masking-ise/extern/scarv-cpu/external/xcrypto/rtl/xc_malu/xc_malu.v"
#    "/home/work/scarv/scarv-soc-masking-ise/extern/scarv-cpu/external/xcrypto/rtl/xc_malu/xc_malu_divrem.v"
#    "/home/work/scarv/scarv-soc-masking-ise/extern/scarv-cpu/external/xcrypto/rtl/xc_malu/xc_malu_long.v"
#    "/home/work/scarv/scarv-soc-masking-ise/extern/scarv-cpu/external/xcrypto/rtl/xc_malu/xc_malu_mul.v"
#    "/home/work/scarv/scarv-soc-masking-ise/extern/scarv-cpu/external/xcrypto/rtl/xc_malu/xc_malu_muldivrem.v"
#    "/home/work/scarv/scarv-soc-masking-ise/extern/scarv-cpu/external/xcrypto/rtl/xc_malu/xc_malu_pmul.v"
#    "/home/work/scarv/scarv-soc-masking-ise/extern/scarv-cpu/external/xcrypto/rtl/xc_sha256/xc_sha256.v"
#    "/home/work/scarv/scarv-soc-masking-ise/extern/scarv-cpu/external/xcrypto/rtl/xc_sha3/xc_sha3.v"
#    "/home/work/scarv/scarv-soc-masking-ise/rtl/soc/scarv_soc.v"
#    "/home/work/scarv/scarv-soc-masking-ise/flow/xilinx/constraints-cw305.xdc"
#    "/home/work/scarv/scarv-soc-masking-ise/verif/xilinx/tb_top_cw305.v"
#
#*****************************************************************************************

# Set the reference directory for source file relative paths (by default the value is script directory path)
set origin_dir "."

# Use origin directory path location variable, if specified in the tcl shell
if { [info exists ::origin_dir_loc] } {
  set origin_dir $::origin_dir_loc
}

# Set the project name
set _xil_proj_name_ "scarv-soc-masking-ise-cw305"

# Use project name variable, if specified in the tcl shell
if { [info exists ::user_project_name] } {
  set _xil_proj_name_ $::user_project_name
}

variable script_file
set script_file "scarv-soc-project-cw305.tcl"

# Help information for this script
proc print_help {} {
  variable script_file
  puts "\nDescription:"
  puts "Recreate a Vivado project from this script. The created project will be"
  puts "functionally equivalent to the original project for which this script was"
  puts "generated. The script contains commands for creating a project, filesets,"
  puts "runs, adding/importing sources and setting properties on various objects.\n"
  puts "Syntax:"
  puts "$script_file"
  puts "$script_file -tclargs \[--origin_dir <path>\]"
  puts "$script_file -tclargs \[--project_name <name>\]"
  puts "$script_file -tclargs \[--help\]\n"
  puts "Usage:"
  puts "Name                   Description"
  puts "-------------------------------------------------------------------------"
  puts "\[--origin_dir <path>\]  Determine source file paths wrt this path. Default"
  puts "                       origin_dir path value is \".\", otherwise, the value"
  puts "                       that was set with the \"-paths_relative_to\" switch"
  puts "                       when this script was generated.\n"
  puts "\[--project_name <name>\] Create project with the specified name. Default"
  puts "                       name is the name of the project from where this"
  puts "                       script was generated.\n"
  puts "\[--help\]               Print help information for this script"
  puts "-------------------------------------------------------------------------\n"
  exit 0
}

if { $::argc > 0 } {
  for {set i 0} {$i < $::argc} {incr i} {
    set option [string trim [lindex $::argv $i]]
    switch -regexp -- $option {
      "--origin_dir"   { incr i; set origin_dir [lindex $::argv $i] }
      "--project_name" { incr i; set _xil_proj_name_ [lindex $::argv $i] }
      "--help"         { print_help }
      default {
        if { [regexp {^-} $option] } {
          puts "ERROR: Unknown option '$option' specified, please type '$script_file -tclargs --help' for usage info.\n"
          return 1
        }
      }
    }
  }
}

# Set the directory path for the original project from where this script was exported
set orig_proj_dir "[file normalize "$origin_dir/../../work/scarv-soc-template"]"

# Create project
create_project ${_xil_proj_name_} ./${_xil_proj_name_} -part xc7a100tftg256-3

# Set the directory path for the new project
set proj_dir [get_property directory [current_project]]

# Set project properties
set obj [current_project]
set_property -name "default_lib" -value "xil_defaultlib" -objects $obj
set_property -name "enable_vhdl_2008" -value "1" -objects $obj
set_property -name "ip_cache_permissions" -value "read write" -objects $obj
set_property -name "ip_output_repo" -value "$proj_dir/${_xil_proj_name_}.cache/ip" -objects $obj
set_property -name "mem.enable_memory_map_generation" -value "1" -objects $obj
set_property -name "part" -value "xc7a100tftg256-3" -objects $obj
set_property -name "sim.central_dir" -value "$proj_dir/${_xil_proj_name_}.ip_user_files" -objects $obj
set_property -name "sim.ip.auto_export_scripts" -value "1" -objects $obj
set_property -name "simulator_language" -value "Mixed" -objects $obj
set_property -name "webtalk.activehdl_export_sim" -value "6" -objects $obj
set_property -name "webtalk.ies_export_sim" -value "6" -objects $obj
set_property -name "webtalk.modelsim_export_sim" -value "6" -objects $obj
set_property -name "webtalk.questa_export_sim" -value "6" -objects $obj
set_property -name "webtalk.riviera_export_sim" -value "6" -objects $obj
set_property -name "webtalk.vcs_export_sim" -value "6" -objects $obj
set_property -name "webtalk.xcelium_export_sim" -value "1" -objects $obj
set_property -name "webtalk.xsim_export_sim" -value "6" -objects $obj
set_property -name "webtalk.xsim_launch_sim" -value "36" -objects $obj
set_property -name "xpm_libraries" -value "XPM_CDC XPM_MEMORY" -objects $obj

# Create 'sources_1' fileset (if not found)
if {[string equal [get_filesets -quiet sources_1] ""]} {
  create_fileset -srcset sources_1
}

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 [file normalize "$::env(XCRYPTO_RTL)/b_bop/b_bop.v"] \
 [file normalize "$::env(XCRYPTO_RTL)/b_lut/b_lut.v"] \
 [file normalize "$::env(SCARV_CPU)/rtl/core/frv_common.vh"] \
 [file normalize "$::env(SCARV_CPU)/rtl/core/frv_alu.v"] \
 [file normalize "$::env(SOC_HOME)/extern/scarv-cpu/rtl/core/frv_asi.v"] \
 [file normalize "$::env(SOC_HOME)/extern/scarv-cpu/rtl/core/frv_bitwise.v"] \
 [file normalize "$::env(SOC_HOME)/extern/scarv-cpu/rtl/core/frv_core.v"] \
 [file normalize "$::env(SOC_HOME)/extern/scarv-cpu/rtl/core/frv_core_fetch_buffer.v"] \
 [file normalize "$::env(SOC_HOME)/extern/scarv-cpu/rtl/core/frv_counters.v"] \
 [file normalize "$::env(SOC_HOME)/extern/scarv-cpu/rtl/core/frv_csrs.v"] \
 [file normalize "$::env(SOC_HOME)/extern/scarv-cpu/rtl/core/frv_gf256_aff.v"] \
 [file normalize "$::env(SOC_HOME)/extern/scarv-cpu/rtl/core/frv_gf256_mul.v"] \
 [file normalize "$::env(SOC_HOME)/extern/scarv-cpu/rtl/core/frv_gprs.v"] \
 [file normalize "$::env(SOC_HOME)/extern/scarv-cpu/rtl/core/frv_interrupts.v"] \
 [file normalize "$::env(SOC_HOME)/extern/scarv-cpu/rtl/core/frv_leak.v"] \
 [file normalize "$::env(SOC_HOME)/extern/scarv-cpu/rtl/core/frv_lfsr32.v"] \
 [file normalize "$::env(SOC_HOME)/extern/scarv-cpu/rtl/core/frv_lsu.v"] \
 [file normalize "$::env(SOC_HOME)/extern/scarv-cpu/rtl/core/frv_masked_alu.v"] \
 [file normalize "$::env(SOC_HOME)/extern/scarv-cpu/rtl/core/frv_masked_arith.v"] \
 [file normalize "$::env(SOC_HOME)/extern/scarv-cpu/rtl/core/frv_masked_barith.v"] \
 [file normalize "$::env(SOC_HOME)/extern/scarv-cpu/rtl/core/frv_masked_bitwise.v"] \
 [file normalize "$::env(SOC_HOME)/extern/scarv-cpu/rtl/core/frv_masked_faff.v"] \
 [file normalize "$::env(SOC_HOME)/extern/scarv-cpu/rtl/core/frv_masked_fmul.v"] \
 [file normalize "$::env(SOC_HOME)/extern/scarv-cpu/rtl/core/frv_masked_shfrot.v"] \
 [file normalize "$::env(SOC_HOME)/extern/scarv-cpu/rtl/core/frv_masked_shuffle.v"] \
 [file normalize "$::env(SOC_HOME)/extern/scarv-cpu/rtl/core/frv_pipeline.v"] \
 [file normalize "$::env(SOC_HOME)/extern/scarv-cpu/rtl/core/frv_pipeline_decode.vh"] \
 [file normalize "$::env(SOC_HOME)/extern/scarv-cpu/rtl/core/frv_pipeline_decode.v"] \
 [file normalize "$::env(SOC_HOME)/extern/scarv-cpu/rtl/core/frv_pipeline_execute.v"] \
 [file normalize "$::env(SOC_HOME)/extern/scarv-cpu/rtl/core/frv_pipeline_fetch.v"] \
 [file normalize "$::env(SOC_HOME)/extern/scarv-cpu/rtl/core/frv_pipeline_memory.v"] \
 [file normalize "$::env(SOC_HOME)/extern/scarv-cpu/rtl/core/frv_pipeline_register.v"] \
 [file normalize "$::env(SOC_HOME)/extern/scarv-cpu/rtl/core/frv_pipeline_writeback.v"] \
 [file normalize "$::env(SOC_HOME)/extern/scarv-cpu/rtl/core/frv_rngif.v"] \
 [file normalize "$::env(SOC_HOME)/extern/scarv-cpu/rtl/core/frv_trng.v"] \
 [file normalize "$::env(SOC_HOME)/rtl/ic/ic_addr_decode.v"] \
 [file normalize "$::env(SOC_HOME)/rtl/ic/ic_cpu_bus_axi_bridge.v"] \
 [file normalize "$::env(SOC_HOME)/rtl/ic/ic_cpu_bus_bram_bridge.v"] \
 [file normalize "$::env(SOC_HOME)/rtl/ic/ic_error_rsp_stub.v"] \
 [file normalize "$::env(SOC_HOME)/rtl/ic/ic_rsp_tracker.v"] \
 [file normalize "$::env(SOC_HOME)/rtl/ic/ic_top.v"] \
 [file normalize "$::env(XCRYPTO_RTL)/p_addsub/p_addsub.v"] \
 [file normalize "$::env(XCRYPTO_RTL)/p_shfrot/p_shfrot.v"] \
 [file normalize "$::env(SOC_HOME)/rtl/rng/scarv_rng_lfsr.v"] \
 [file normalize "$::env(SOC_HOME)/rtl/rng/scarv_rng_top.v"] \
 [file normalize "$::env(SOC_HOME)/rtl/mem/scarv_soc_bram_dual_synth_xilinx_xc7k.v"] \
 [file normalize "$::env(XCRYPTO_RTL)/xc_aesmix/xc_aesmix.v"] \
 [file normalize "$::env(XCRYPTO_RTL)/xc_aessub/xc_aessub.v"] \
 [file normalize "$::env(XCRYPTO_RTL)/xc_aessub/xc_aessub_sbox.v"] \
 [file normalize "$::env(XCRYPTO_RTL)/xc_malu/xc_malu.v"] \
 [file normalize "$::env(XCRYPTO_RTL)/xc_malu/xc_malu_divrem.v"] \
 [file normalize "$::env(XCRYPTO_RTL)/xc_malu/xc_malu_long.v"] \
 [file normalize "$::env(XCRYPTO_RTL)/xc_malu/xc_malu_mul.v"] \
 [file normalize "$::env(XCRYPTO_RTL)/xc_malu/xc_malu_muldivrem.v"] \
 [file normalize "$::env(XCRYPTO_RTL)/xc_malu/xc_malu_pmul.v"] \
 [file normalize "$::env(XCRYPTO_RTL)/xc_sha256/xc_sha256.v"] \
 [file normalize "$::env(XCRYPTO_RTL)/xc_sha3/xc_sha3.v"] \
 [file normalize "$::env(SOC_HOME)/rtl/soc/scarv_soc.v"] \
]
add_files -norecurse -fileset $obj $files

# Import local files from the original project
set files [list \
 [file normalize "$::env(SOC_HOME)/rtl/xilinx/system_top_wrapper_cw305.v" ]\
]
set imported_files [import_files -fileset sources_1 $files]

# Set 'sources_1' fileset file properties for remote files
set file "$::env(SCARV_CPU)/rtl/core/frv_common.vh"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "Verilog Header" -objects $file_obj

set file "$::env(SCARV_CPU)/rtl/core/frv_pipeline_decode.vh"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "Verilog Header" -objects $file_obj


# Set 'sources_1' fileset file properties for local files
# None

# Set 'sources_1' fileset properties
set obj [get_filesets sources_1]
set_property -name "top" -value "system_top_wrapper_wrapper" -objects $obj
set_property -name "top_auto_set" -value "0" -objects $obj

# Create 'constrs_1' fileset (if not found)
if {[string equal [get_filesets -quiet constrs_1] ""]} {
  create_fileset -constrset constrs_1
}

# Set 'constrs_1' fileset object
set obj [get_filesets constrs_1]

# Add/Import constrs file and set constrs file properties
set file "[file normalize "$::env(SOC_HOME)/flow/xilinx/constraints-cw305.xdc"]"
set file_added [add_files -norecurse -fileset $obj [list $file]]
set file "$::env(SOC_HOME)/flow/xilinx/constraints-cw305.xdc"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets constrs_1] [list "*$file"]]
set_property -name "file_type" -value "XDC" -objects $file_obj

# Set 'constrs_1' fileset properties
set obj [get_filesets constrs_1]
set_property -name "target_constrs_file" -value "[file normalize "$::env(SOC_HOME)/flow/xilinx/constraints-cw305.xdc"]" -objects $obj
set_property -name "target_part" -value "xc7a100tftg256-3" -objects $obj
set_property -name "target_ucf" -value "[file normalize "$::env(SOC_HOME)/flow/xilinx/constraints-cw305.xdc"]" -objects $obj

# Create 'sim_1' fileset (if not found)
if {[string equal [get_filesets -quiet sim_1] ""]} {
  create_fileset -simset sim_1
}

# Set 'sim_1' fileset object
set obj [get_filesets sim_1]
set files [list \
 [file normalize "$::env(SOC_HOME)/verif/xilinx/tb_top_cw305.v"] \
]
add_files -norecurse -fileset $obj $files

# Import local files from the original project
set files [list \
 [file normalize "$::env(SOC_HOME)/flow/xilinx/tb_top_behav.wcfg" ]\
]
set imported_files [import_files -fileset sim_1 $files]

# Set 'sim_1' fileset file properties for remote files
# None

# Set 'sim_1' fileset file properties for local files
# None

# Set 'sim_1' fileset properties
set obj [get_filesets sim_1]
set_property -name "top" -value "tb_top" -objects $obj
set_property -name "top_auto_set" -value "0" -objects $obj
set_property -name "top_lib" -value "xil_defaultlib" -objects $obj

# Set 'utils_1' fileset object
set obj [get_filesets utils_1]
# Empty (no sources present)

# Set 'utils_1' fileset properties
set obj [get_filesets utils_1]


# Adding sources referenced in BDs, if not already added
if { [get_files b_bop.v] == "" } {
  import_files -quiet -fileset sources_1 $::env(SOC_HOME)/extern/scarv-cpu/external/xcrypto/rtl/b_bop/b_bop.v
}
if { [get_files b_lut.v] == "" } {
  import_files -quiet -fileset sources_1 $::env(SOC_HOME)/extern/scarv-cpu/external/xcrypto/rtl/b_lut/b_lut.v
}
if { [get_files frv_common.vh] == "" } {
  import_files -quiet -fileset sources_1 $::env(SOC_HOME)/extern/scarv-cpu/rtl/core/frv_common.vh
}
if { [get_files frv_alu.v] == "" } {
  import_files -quiet -fileset sources_1 $::env(SOC_HOME)/extern/scarv-cpu/rtl/core/frv_alu.v
}
if { [get_files frv_asi.v] == "" } {
  import_files -quiet -fileset sources_1 $::env(SOC_HOME)/extern/scarv-cpu/rtl/core/frv_asi.v
}
if { [get_files frv_bitwise.v] == "" } {
  import_files -quiet -fileset sources_1 $::env(SOC_HOME)/extern/scarv-cpu/rtl/core/frv_bitwise.v
}
if { [get_files frv_core.v] == "" } {
  import_files -quiet -fileset sources_1 $::env(SOC_HOME)/extern/scarv-cpu/rtl/core/frv_core.v
}
if { [get_files frv_core_fetch_buffer.v] == "" } {
  import_files -quiet -fileset sources_1 $::env(SOC_HOME)/extern/scarv-cpu/rtl/core/frv_core_fetch_buffer.v
}
if { [get_files frv_counters.v] == "" } {
  import_files -quiet -fileset sources_1 $::env(SOC_HOME)/extern/scarv-cpu/rtl/core/frv_counters.v
}
if { [get_files frv_csrs.v] == "" } {
  import_files -quiet -fileset sources_1 $::env(SOC_HOME)/extern/scarv-cpu/rtl/core/frv_csrs.v
}
if { [get_files frv_gf256_aff.v] == "" } {
  import_files -quiet -fileset sources_1 $::env(SOC_HOME)/extern/scarv-cpu/rtl/core/frv_gf256_aff.v
}
if { [get_files frv_gf256_mul.v] == "" } {
  import_files -quiet -fileset sources_1 $::env(SOC_HOME)/extern/scarv-cpu/rtl/core/frv_gf256_mul.v
}
if { [get_files frv_gprs.v] == "" } {
  import_files -quiet -fileset sources_1 $::env(SOC_HOME)/extern/scarv-cpu/rtl/core/frv_gprs.v
}
if { [get_files frv_interrupts.v] == "" } {
  import_files -quiet -fileset sources_1 $::env(SOC_HOME)/extern/scarv-cpu/rtl/core/frv_interrupts.v
}
if { [get_files frv_leak.v] == "" } {
  import_files -quiet -fileset sources_1 $::env(SOC_HOME)/extern/scarv-cpu/rtl/core/frv_leak.v
}
if { [get_files frv_lfsr32.v] == "" } {
  import_files -quiet -fileset sources_1 $::env(SOC_HOME)/extern/scarv-cpu/rtl/core/frv_lfsr32.v
}
if { [get_files frv_lsu.v] == "" } {
  import_files -quiet -fileset sources_1 $::env(SOC_HOME)/extern/scarv-cpu/rtl/core/frv_lsu.v
}
if { [get_files frv_masked_alu.v] == "" } {
  import_files -quiet -fileset sources_1 $::env(SOC_HOME)/extern/scarv-cpu/rtl/core/frv_masked_alu.v
}
if { [get_files frv_masked_arith.v] == "" } {
  import_files -quiet -fileset sources_1 $::env(SOC_HOME)/extern/scarv-cpu/rtl/core/frv_masked_arith.v
}
if { [get_files frv_masked_barith.v] == "" } {
  import_files -quiet -fileset sources_1 $::env(SOC_HOME)/extern/scarv-cpu/rtl/core/frv_masked_barith.v
}
if { [get_files frv_masked_bitwise.v] == "" } {
  import_files -quiet -fileset sources_1 $::env(SOC_HOME)/extern/scarv-cpu/rtl/core/frv_masked_bitwise.v
}
if { [get_files frv_masked_faff.v] == "" } {
  import_files -quiet -fileset sources_1 $::env(SOC_HOME)/extern/scarv-cpu/rtl/core/frv_masked_faff.v
}
if { [get_files frv_masked_fmul.v] == "" } {
  import_files -quiet -fileset sources_1 $::env(SOC_HOME)/extern/scarv-cpu/rtl/core/frv_masked_fmul.v
}
if { [get_files frv_masked_shfrot.v] == "" } {
  import_files -quiet -fileset sources_1 $::env(SOC_HOME)/extern/scarv-cpu/rtl/core/frv_masked_shfrot.v
}
if { [get_files frv_masked_shuffle.v] == "" } {
  import_files -quiet -fileset sources_1 $::env(SOC_HOME)/extern/scarv-cpu/rtl/core/frv_masked_shuffle.v
}
if { [get_files frv_pipeline.v] == "" } {
  import_files -quiet -fileset sources_1 $::env(SOC_HOME)/extern/scarv-cpu/rtl/core/frv_pipeline.v
}
if { [get_files frv_pipeline_decode.vh] == "" } {
  import_files -quiet -fileset sources_1 $::env(SOC_HOME)/extern/scarv-cpu/rtl/core/frv_pipeline_decode.vh
}
if { [get_files frv_pipeline_decode.v] == "" } {
  import_files -quiet -fileset sources_1 $::env(SOC_HOME)/extern/scarv-cpu/rtl/core/frv_pipeline_decode.v
}
if { [get_files frv_pipeline_execute.v] == "" } {
  import_files -quiet -fileset sources_1 $::env(SOC_HOME)/extern/scarv-cpu/rtl/core/frv_pipeline_execute.v
}
if { [get_files frv_pipeline_fetch.v] == "" } {
  import_files -quiet -fileset sources_1 $::env(SOC_HOME)/extern/scarv-cpu/rtl/core/frv_pipeline_fetch.v
}
if { [get_files frv_pipeline_memory.v] == "" } {
  import_files -quiet -fileset sources_1 $::env(SOC_HOME)/extern/scarv-cpu/rtl/core/frv_pipeline_memory.v
}
if { [get_files frv_pipeline_register.v] == "" } {
  import_files -quiet -fileset sources_1 $::env(SOC_HOME)/extern/scarv-cpu/rtl/core/frv_pipeline_register.v
}
if { [get_files frv_pipeline_writeback.v] == "" } {
  import_files -quiet -fileset sources_1 $::env(SOC_HOME)/extern/scarv-cpu/rtl/core/frv_pipeline_writeback.v
}
if { [get_files frv_rngif.v] == "" } {
  import_files -quiet -fileset sources_1 $::env(SOC_HOME)/extern/scarv-cpu/rtl/core/frv_rngif.v
}
if { [get_files frv_trng.v] == "" } {
  import_files -quiet -fileset sources_1 $::env(SOC_HOME)/extern/scarv-cpu/rtl/core/frv_trng.v
}
if { [get_files ic_addr_decode.v] == "" } {
  import_files -quiet -fileset sources_1 $::env(SOC_HOME)/rtl/ic/ic_addr_decode.v
}
if { [get_files ic_cpu_bus_axi_bridge.v] == "" } {
  import_files -quiet -fileset sources_1 $::env(SOC_HOME)/rtl/ic/ic_cpu_bus_axi_bridge.v
}
if { [get_files ic_cpu_bus_bram_bridge.v] == "" } {
  import_files -quiet -fileset sources_1 $::env(SOC_HOME)/rtl/ic/ic_cpu_bus_bram_bridge.v
}
if { [get_files ic_error_rsp_stub.v] == "" } {
  import_files -quiet -fileset sources_1 $::env(SOC_HOME)/rtl/ic/ic_error_rsp_stub.v
}
if { [get_files ic_rsp_tracker.v] == "" } {
  import_files -quiet -fileset sources_1 $::env(SOC_HOME)/rtl/ic/ic_rsp_tracker.v
}
if { [get_files ic_top.v] == "" } {
  import_files -quiet -fileset sources_1 $::env(SOC_HOME)/rtl/ic/ic_top.v
}
if { [get_files p_addsub.v] == "" } {
  import_files -quiet -fileset sources_1 $::env(SOC_HOME)/extern/scarv-cpu/external/xcrypto/rtl/p_addsub/p_addsub.v
}
if { [get_files p_shfrot.v] == "" } {
  import_files -quiet -fileset sources_1 $::env(SOC_HOME)/extern/scarv-cpu/external/xcrypto/rtl/p_shfrot/p_shfrot.v
}
if { [get_files scarv_rng_lfsr.v] == "" } {
  import_files -quiet -fileset sources_1 $::env(SOC_HOME)/rtl/rng/scarv_rng_lfsr.v
}
if { [get_files scarv_rng_top.v] == "" } {
  import_files -quiet -fileset sources_1 $::env(SOC_HOME)/rtl/rng/scarv_rng_top.v
}
if { [get_files scarv_soc_bram_dual_synth_xilinx_xc7k.v] == "" } {
  import_files -quiet -fileset sources_1 $::env(SOC_HOME)/rtl/mem/scarv_soc_bram_dual_synth_xilinx_xc7k.v
}
if { [get_files xc_aesmix.v] == "" } {
  import_files -quiet -fileset sources_1 $::env(SOC_HOME)/extern/scarv-cpu/external/xcrypto/rtl/xc_aesmix/xc_aesmix.v
}
if { [get_files xc_aessub.v] == "" } {
  import_files -quiet -fileset sources_1 $::env(SOC_HOME)/extern/scarv-cpu/external/xcrypto/rtl/xc_aessub/xc_aessub.v
}
if { [get_files xc_aessub_sbox.v] == "" } {
  import_files -quiet -fileset sources_1 $::env(SOC_HOME)/extern/scarv-cpu/external/xcrypto/rtl/xc_aessub/xc_aessub_sbox.v
}
if { [get_files xc_malu.v] == "" } {
  import_files -quiet -fileset sources_1 $::env(SOC_HOME)/extern/scarv-cpu/external/xcrypto/rtl/xc_malu/xc_malu.v
}
if { [get_files xc_malu_divrem.v] == "" } {
  import_files -quiet -fileset sources_1 $::env(SOC_HOME)/extern/scarv-cpu/external/xcrypto/rtl/xc_malu/xc_malu_divrem.v
}
if { [get_files xc_malu_long.v] == "" } {
  import_files -quiet -fileset sources_1 $::env(SOC_HOME)/extern/scarv-cpu/external/xcrypto/rtl/xc_malu/xc_malu_long.v
}
if { [get_files xc_malu_mul.v] == "" } {
  import_files -quiet -fileset sources_1 $::env(SOC_HOME)/extern/scarv-cpu/external/xcrypto/rtl/xc_malu/xc_malu_mul.v
}
if { [get_files xc_malu_muldivrem.v] == "" } {
  import_files -quiet -fileset sources_1 $::env(SOC_HOME)/extern/scarv-cpu/external/xcrypto/rtl/xc_malu/xc_malu_muldivrem.v
}
if { [get_files xc_malu_pmul.v] == "" } {
  import_files -quiet -fileset sources_1 $::env(SOC_HOME)/extern/scarv-cpu/external/xcrypto/rtl/xc_malu/xc_malu_pmul.v
}
if { [get_files xc_sha256.v] == "" } {
  import_files -quiet -fileset sources_1 $::env(SOC_HOME)/extern/scarv-cpu/external/xcrypto/rtl/xc_sha256/xc_sha256.v
}
if { [get_files xc_sha3.v] == "" } {
  import_files -quiet -fileset sources_1 $::env(SOC_HOME)/extern/scarv-cpu/external/xcrypto/rtl/xc_sha3/xc_sha3.v
}
if { [get_files scarv_soc.v] == "" } {
  import_files -quiet -fileset sources_1 $::env(SOC_HOME)/rtl/soc/scarv_soc.v
}


# Proc to create BD system_top_wrapper
proc cr_bd_system_top_wrapper { parentCell } {
# The design that will be created by this Tcl proc contains the following 
# module references:
# scarv_soc



  # CHANGE DESIGN NAME HERE
  set design_name system_top_wrapper

  common::send_msg_id "BD_TCL-003" "INFO" "Currently there is no design <$design_name> in project, so creating one..."

  create_bd_design $design_name

  set bCheckIPsPassed 1
  ##################################################################
  # CHECK IPs
  ##################################################################
  set bCheckIPs 1
  if { $bCheckIPs == 1 } {
     set list_check_ips "\ 
  xilinx.com:ip:axi_gpio:2.0\
  xilinx.com:ip:axi_uartlite:2.0\
  xilinx.com:ip:clk_wiz:6.0\
  xilinx.com:ip:proc_sys_reset:5.0\
  xilinx.com:ip:xlconstant:1.1\
  "

   set list_ips_missing ""
   common::send_msg_id "BD_TCL-006" "INFO" "Checking if the following IPs exist in the project's IP catalog: $list_check_ips ."

   foreach ip_vlnv $list_check_ips {
      set ip_obj [get_ipdefs -all $ip_vlnv]
      if { $ip_obj eq "" } {
         lappend list_ips_missing $ip_vlnv
      }
   }

   if { $list_ips_missing ne "" } {
      catch {common::send_msg_id "BD_TCL-115" "ERROR" "The following IPs are not found in the IP Catalog:\n  $list_ips_missing\n\nResolution: Please add the repository containing the IP(s) to the project." }
      set bCheckIPsPassed 0
   }

  }

  ##################################################################
  # CHECK Modules
  ##################################################################
  set bCheckModules 1
  if { $bCheckModules == 1 } {
     set list_check_mods "\ 
  scarv_soc\
  "

   set list_mods_missing ""
   common::send_msg_id "BD_TCL-006" "INFO" "Checking if the following modules exist in the project's sources: $list_check_mods ."

   foreach mod_vlnv $list_check_mods {
      if { [can_resolve_reference $mod_vlnv] == 0 } {
         lappend list_mods_missing $mod_vlnv
      }
   }

   if { $list_mods_missing ne "" } {
      catch {common::send_msg_id "BD_TCL-115" "ERROR" "The following module(s) are not found in the project: $list_mods_missing" }
      common::send_msg_id "BD_TCL-008" "INFO" "Please add source files for the missing module(s) above."
      set bCheckIPsPassed 0
   }
}

  if { $bCheckIPsPassed != 1 } {
    common::send_msg_id "BD_TCL-1003" "WARNING" "Will not continue with creation of design due to the error(s) above."
    return 3
  }

  variable script_folder

  if { $parentCell eq "" } {
     set parentCell [get_bd_cells /]
  }

  # Get object for parentCell
  set parentObj [get_bd_cells $parentCell]
  if { $parentObj == "" } {
     catch {common::send_msg_id "BD_TCL-100" "ERROR" "Unable to find parent cell <$parentCell>!"}
     return
  }

  # Make sure parentObj is hier blk
  set parentType [get_property TYPE $parentObj]
  if { $parentType ne "hier" } {
     catch {common::send_msg_id "BD_TCL-101" "ERROR" "Parent <$parentObj> has TYPE = <$parentType>. Expected to be <hier>."}
     return
  }

  # Save current instance; Restore later
  set oldCurInst [current_bd_instance .]

  # Set parent object as current
  current_bd_instance $parentObj


  # Create interface ports
  set gpio_led [ create_bd_intf_port -mode Master -vlnv xilinx.com:interface:gpio_rtl:1.0 gpio_led ]

  set gpio_trig [ create_bd_intf_port -mode Master -vlnv xilinx.com:interface:gpio_rtl:1.0 gpio_trig ]

  set uart [ create_bd_intf_port -mode Master -vlnv xilinx.com:interface:uart_rtl:1.0 uart ]


  # Create ports
  set sys_clk [ create_bd_port -dir I -type clk -freq_hz 100000000 sys_clk ]
  set sys_reset [ create_bd_port -dir I -type rst sys_reset ]
  set_property -dict [ list \
   CONFIG.POLARITY {ACTIVE_LOW} \
 ] $sys_reset

  # Create instance: axi_gpio_0, and set properties
  set axi_gpio_0 [ create_bd_cell -type ip -vlnv xilinx.com:ip:axi_gpio:2.0 axi_gpio_0 ]
  set_property -dict [ list \
   CONFIG.C_ALL_OUTPUTS {1} \
   CONFIG.C_ALL_OUTPUTS_2 {1} \
   CONFIG.C_GPIO2_WIDTH {10} \
   CONFIG.C_GPIO_WIDTH {1} \
   CONFIG.C_IS_DUAL {1} \
 ] $axi_gpio_0

  # Create instance: axi_interconnect_0, and set properties
  set axi_interconnect_0 [ create_bd_cell -type ip -vlnv xilinx.com:ip:axi_interconnect:2.1 axi_interconnect_0 ]

  # Create instance: axi_uartlite_0, and set properties
  set axi_uartlite_0 [ create_bd_cell -type ip -vlnv xilinx.com:ip:axi_uartlite:2.0 axi_uartlite_0 ]
  set_property -dict [ list \
   CONFIG.C_BAUDRATE {128000} \
 ] $axi_uartlite_0

  # Create instance: clk_wiz_0, and set properties
  set clk_wiz_0 [ create_bd_cell -type ip -vlnv xilinx.com:ip:clk_wiz:6.0 clk_wiz_0 ]
  set_property -dict [ list \
   CONFIG.CLKOUT1_JITTER {151.636} \
   CONFIG.CLKOUT1_REQUESTED_OUT_FREQ {50} \
   CONFIG.MMCM_CLKOUT0_DIVIDE_F {20.000} \
   CONFIG.RESET_PORT {resetn} \
   CONFIG.RESET_TYPE {ACTIVE_LOW} \
 ] $clk_wiz_0

  # Create instance: proc_sys_reset_0, and set properties
  set proc_sys_reset_0 [ create_bd_cell -type ip -vlnv xilinx.com:ip:proc_sys_reset:5.0 proc_sys_reset_0 ]

  # Create instance: scarv_soc_0, and set properties
  set block_name scarv_soc
  set block_cell_name scarv_soc_0
  if { [catch {set scarv_soc_0 [create_bd_cell -type module -reference $block_name $block_cell_name] } errmsg] } {
     catch {common::send_msg_id "BD_TCL-105" "ERROR" "Unable to add referenced block <$block_name>. Please add the files for ${block_name}'s definition into the project."}
     return 1
   } elseif { $scarv_soc_0 eq "" } {
     catch {common::send_msg_id "BD_TCL-106" "ERROR" "Unable to referenced block <$block_name>. Please add the files for ${block_name}'s definition into the project."}
     return 1
   }
    set_property -dict [ list \
   CONFIG.BRAM_ROM_MEMH_FILE {/home/work/scarv/scarv-soc-masking-ise/work/fsbl/fsbl-vivado.hex} \
 ] $scarv_soc_0

  # Create instance: xlconstant_0, and set properties
  set xlconstant_0 [ create_bd_cell -type ip -vlnv xilinx.com:ip:xlconstant:1.1 xlconstant_0 ]
  set_property -dict [ list \
   CONFIG.CONST_VAL {0} \
 ] $xlconstant_0

  # Create instance: xlconstant_1, and set properties
  set xlconstant_1 [ create_bd_cell -type ip -vlnv xilinx.com:ip:xlconstant:1.1 xlconstant_1 ]
  set_property -dict [ list \
   CONFIG.CONST_VAL {0} \
   CONFIG.CONST_WIDTH {4} \
 ] $xlconstant_1

  # Create interface connections
  connect_bd_intf_net -intf_net S00_AXI_1 [get_bd_intf_pins axi_interconnect_0/S00_AXI] [get_bd_intf_pins scarv_soc_0/m0]
  connect_bd_intf_net -intf_net axi_gpio_0_GPIO [get_bd_intf_ports gpio_trig] [get_bd_intf_pins axi_gpio_0/GPIO]
  connect_bd_intf_net -intf_net axi_gpio_0_GPIO2 [get_bd_intf_ports gpio_led] [get_bd_intf_pins axi_gpio_0/GPIO2]
  connect_bd_intf_net -intf_net axi_interconnect_0_M00_AXI [get_bd_intf_pins axi_interconnect_0/M00_AXI] [get_bd_intf_pins axi_uartlite_0/S_AXI]
  connect_bd_intf_net -intf_net axi_interconnect_0_M01_AXI [get_bd_intf_pins axi_gpio_0/S_AXI] [get_bd_intf_pins axi_interconnect_0/M01_AXI]
  connect_bd_intf_net -intf_net axi_uartlite_0_UART [get_bd_intf_ports uart] [get_bd_intf_pins axi_uartlite_0/UART]
  
  set_property CONFIG.FREQ_HZ 50000000 [get_bd_intf_pins scarv_soc_0/m0]

  # Create port connections
  connect_bd_net -net clk_100MHz_1 [get_bd_ports sys_clk] [get_bd_pins clk_wiz_0/clk_in1]
  connect_bd_net -net clk_wiz_0_clk_out1 [get_bd_pins axi_gpio_0/s_axi_aclk] [get_bd_pins axi_interconnect_0/ACLK] [get_bd_pins axi_interconnect_0/M00_ACLK] [get_bd_pins axi_interconnect_0/M01_ACLK] [get_bd_pins axi_interconnect_0/S00_ACLK] [get_bd_pins axi_uartlite_0/s_axi_aclk] [get_bd_pins clk_wiz_0/clk_out1] [get_bd_pins proc_sys_reset_0/slowest_sync_clk] [get_bd_pins scarv_soc_0/g_clk]
  connect_bd_net -net proc_sys_reset_0_peripheral_aresetn [get_bd_pins axi_gpio_0/s_axi_aresetn] [get_bd_pins axi_interconnect_0/ARESETN] [get_bd_pins axi_interconnect_0/M00_ARESETN] [get_bd_pins axi_interconnect_0/M01_ARESETN] [get_bd_pins axi_interconnect_0/S00_ARESETN] [get_bd_pins axi_uartlite_0/s_axi_aresetn] [get_bd_pins proc_sys_reset_0/peripheral_aresetn] [get_bd_pins scarv_soc_0/g_resetn]
  connect_bd_net -net reset_rtl_0_1 [get_bd_ports sys_reset] [get_bd_pins clk_wiz_0/resetn] [get_bd_pins proc_sys_reset_0/ext_reset_in]
  connect_bd_net -net xlconstant_0_dout [get_bd_pins scarv_soc_0/cpu_int_external] [get_bd_pins scarv_soc_0/cpu_int_nmi] [get_bd_pins scarv_soc_0/cpu_int_software] [get_bd_pins xlconstant_0/dout]
  connect_bd_net -net xlconstant_1_dout [get_bd_pins scarv_soc_0/cpu_int_ext_cause] [get_bd_pins xlconstant_1/dout]

  # Create address segments
  assign_bd_address -offset 0x40002000 -range 0x00000400 -target_address_space [get_bd_addr_spaces scarv_soc_0/m0] [get_bd_addr_segs axi_gpio_0/S_AXI/Reg] -force
  assign_bd_address -offset 0x40001000 -range 0x00000400 -target_address_space [get_bd_addr_spaces scarv_soc_0/m0] [get_bd_addr_segs axi_uartlite_0/S_AXI/Reg] -force

  # Perform GUI Layout
  regenerate_bd_layout -layout_string {
   "ActiveEmotionalView":"Default View",
   "Default View_ScaleFactor":"0.690214",
   "Default View_TopLeft":"-116,-93",
   "ExpandedHierarchyInLayout":"",
   "guistr":"# # String gsaved with Nlview 7.0.21  2019-05-29 bk=1.5064 VDI=41 GEI=36 GUI=JA:9.0 TLS
#  -string -flagsOSRD
preplace port gpio_trig -pg 1 -lvl 6 -x 1500 -y 440 -defaultsOSRD
preplace port uart -pg 1 -lvl 6 -x 1500 -y 290 -defaultsOSRD
preplace port gpio_led -pg 1 -lvl 6 -x 1500 -y 460 -defaultsOSRD
preplace port sys_clk -pg 1 -lvl 0 -x 0 -y 140 -defaultsOSRD
preplace port sys_reset -pg 1 -lvl 0 -x 0 -y 60 -defaultsOSRD
preplace inst clk_wiz_0 -pg 1 -lvl 1 -x 120 -y 130 -defaultsOSRD
preplace inst proc_sys_reset_0 -pg 1 -lvl 2 -x 410 -y 100 -defaultsOSRD
preplace inst axi_gpio_0 -pg 1 -lvl 5 -x 1360 -y 440 -defaultsOSRD
preplace inst axi_interconnect_0 -pg 1 -lvl 4 -x 1070 -y 410 -defaultsOSRD
preplace inst axi_uartlite_0 -pg 1 -lvl 5 -x 1360 -y 300 -defaultsOSRD
preplace inst scarv_soc_0 -pg 1 -lvl 3 -x 760 -y 330 -defaultsOSRD
preplace inst xlconstant_0 -pg 1 -lvl 2 -x 410 -y 260 -defaultsOSRD
preplace inst xlconstant_1 -pg 1 -lvl 2 -x 410 -y 360 -defaultsOSRD
preplace netloc proc_sys_reset_0_peripheral_aresetn 1 2 3 610 220 910 270 1220
preplace netloc clk_wiz_0_clk_out1 1 1 4 230 200 600 210 920 260 1240
preplace netloc clk_100MHz_1 1 0 1 NJ 140
preplace netloc reset_rtl_0_1 1 0 2 20 60 220
preplace netloc xlconstant_0_dout 1 2 1 590 260n
preplace netloc xlconstant_1_dout 1 2 1 NJ 360
preplace netloc axi_interconnect_0_M01_AXI 1 4 1 N 420
preplace netloc axi_gpio_0_GPIO 1 5 1 1480J 430n
preplace netloc axi_interconnect_0_M00_AXI 1 4 1 1230 280n
preplace netloc axi_uartlite_0_UART 1 5 1 NJ 290
preplace netloc S00_AXI_1 1 3 1 N 330
preplace netloc axi_gpio_0_GPIO2 1 5 1 1480 450n
levelinfo -pg 1 0 120 410 760 1070 1360 1500
pagesize -pg 1 -db -bbox -sgen -120 0 1620 550
"
}

  # Restore current instance
  current_bd_instance $oldCurInst

  validate_bd_design
  save_bd_design
  close_bd_design $design_name 
}
# End of cr_bd_system_top_wrapper()
cr_bd_system_top_wrapper ""
set_property REGISTERED_WITH_MANAGER "1" [get_files system_top_wrapper.bd ] 
set_property SYNTH_CHECKPOINT_MODE "Hierarchical" [get_files system_top_wrapper.bd ] 

# Create 'synth_1' run (if not found)
if {[string equal [get_runs -quiet synth_1] ""]} {
    create_run -name synth_1 -part xc7a100tftg256-3 -flow {Vivado Synthesis 2019} -strategy "Vivado Synthesis Defaults" -report_strategy {No Reports} -constrset constrs_1
} else {
  set_property strategy "Vivado Synthesis Defaults" [get_runs synth_1]
  set_property flow "Vivado Synthesis 2019" [get_runs synth_1]
}
set obj [get_runs synth_1]
set_property set_report_strategy_name 1 $obj
set_property report_strategy {Vivado Synthesis Default Reports} $obj
set_property set_report_strategy_name 0 $obj
# Create 'synth_1_synth_report_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs synth_1] synth_1_synth_report_utilization_0] "" ] } {
  create_report_config -report_name synth_1_synth_report_utilization_0 -report_type report_utilization:1.0 -steps synth_design -runs synth_1
}
set obj [get_report_configs -of_objects [get_runs synth_1] synth_1_synth_report_utilization_0]
if { $obj != "" } {

}
set obj [get_runs synth_1]
set_property -name "part" -value "xc7a100tftg256-3" -objects $obj
set_property -name "strategy" -value "Vivado Synthesis Defaults" -objects $obj

# set the current synth run
current_run -synthesis [get_runs synth_1]

# Create 'impl_1' run (if not found)
if {[string equal [get_runs -quiet impl_1] ""]} {
    create_run -name impl_1 -part xc7a100tftg256-3 -flow {Vivado Implementation 2019} -strategy "Vivado Implementation Defaults" -report_strategy {No Reports} -constrset constrs_1 -parent_run synth_1
} else {
  set_property strategy "Vivado Implementation Defaults" [get_runs impl_1]
  set_property flow "Vivado Implementation 2019" [get_runs impl_1]
}
set obj [get_runs impl_1]
set_property set_report_strategy_name 1 $obj
set_property report_strategy {Vivado Implementation Default Reports} $obj
set_property set_report_strategy_name 0 $obj
# Create 'impl_1_init_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_init_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_init_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps init_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_init_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj

}
# Create 'impl_1_opt_report_drc_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_drc_0] "" ] } {
  create_report_config -report_name impl_1_opt_report_drc_0 -report_type report_drc:1.0 -steps opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_drc_0]
if { $obj != "" } {

}
# Create 'impl_1_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj

}
# Create 'impl_1_power_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_power_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_power_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps power_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_power_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj

}
# Create 'impl_1_place_report_io_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_io_0] "" ] } {
  create_report_config -report_name impl_1_place_report_io_0 -report_type report_io:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_io_0]
if { $obj != "" } {

}
# Create 'impl_1_place_report_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_utilization_0] "" ] } {
  create_report_config -report_name impl_1_place_report_utilization_0 -report_type report_utilization:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_utilization_0]
if { $obj != "" } {

}
# Create 'impl_1_place_report_control_sets_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_control_sets_0] "" ] } {
  create_report_config -report_name impl_1_place_report_control_sets_0 -report_type report_control_sets:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_control_sets_0]
if { $obj != "" } {
set_property -name "options.verbose" -value "1" -objects $obj

}
# Create 'impl_1_place_report_incremental_reuse_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_0] "" ] } {
  create_report_config -report_name impl_1_place_report_incremental_reuse_0 -report_type report_incremental_reuse:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'impl_1_place_report_incremental_reuse_1' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_1] "" ] } {
  create_report_config -report_name impl_1_place_report_incremental_reuse_1 -report_type report_incremental_reuse:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_1]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'impl_1_place_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_place_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj

}
# Create 'impl_1_post_place_power_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_post_place_power_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_post_place_power_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps post_place_power_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_post_place_power_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj

}
# Create 'impl_1_phys_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_phys_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_phys_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps phys_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_phys_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj

}
# Create 'impl_1_route_report_drc_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_drc_0] "" ] } {
  create_report_config -report_name impl_1_route_report_drc_0 -report_type report_drc:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_drc_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_methodology_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_methodology_0] "" ] } {
  create_report_config -report_name impl_1_route_report_methodology_0 -report_type report_methodology:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_methodology_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_power_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_power_0] "" ] } {
  create_report_config -report_name impl_1_route_report_power_0 -report_type report_power:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_power_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_route_status_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_route_status_0] "" ] } {
  create_report_config -report_name impl_1_route_report_route_status_0 -report_type report_route_status:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_route_status_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_route_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_timing_summary_0]
if { $obj != "" } {
set_property -name "options.max_paths" -value "10" -objects $obj

}
# Create 'impl_1_route_report_incremental_reuse_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_incremental_reuse_0] "" ] } {
  create_report_config -report_name impl_1_route_report_incremental_reuse_0 -report_type report_incremental_reuse:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_incremental_reuse_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_clock_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_clock_utilization_0] "" ] } {
  create_report_config -report_name impl_1_route_report_clock_utilization_0 -report_type report_clock_utilization:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_clock_utilization_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_bus_skew_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_bus_skew_0] "" ] } {
  create_report_config -report_name impl_1_route_report_bus_skew_0 -report_type report_bus_skew:1.1 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_bus_skew_0]
if { $obj != "" } {
set_property -name "options.warn_on_violation" -value "1" -objects $obj

}
# Create 'impl_1_post_route_phys_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_post_route_phys_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps post_route_phys_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.warn_on_violation" -value "1" -objects $obj

}
# Create 'impl_1_post_route_phys_opt_report_bus_skew_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_bus_skew_0] "" ] } {
  create_report_config -report_name impl_1_post_route_phys_opt_report_bus_skew_0 -report_type report_bus_skew:1.1 -steps post_route_phys_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_bus_skew_0]
if { $obj != "" } {
set_property -name "options.warn_on_violation" -value "1" -objects $obj

}
set obj [get_runs impl_1]
set_property -name "part" -value "xc7a100tftg256-3" -objects $obj
set_property -name "strategy" -value "Vivado Implementation Defaults" -objects $obj
set_property -name "steps.phys_opt_design.is_enabled" -value "1" -objects $obj
set_property -name "steps.write_bitstream.args.readback_file" -value "0" -objects $obj
set_property -name "steps.write_bitstream.args.verbose" -value "0" -objects $obj

# set the current impl run
current_run -implementation [get_runs impl_1]

puts "INFO: Project created:${_xil_proj_name_}"
# Create 'drc_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "drc_1" ] ] ""]} {
create_dashboard_gadget -name {drc_1} -type drc
}
set obj [get_dashboard_gadgets [ list "drc_1" ] ]
set_property -name "reports" -value "impl_1#impl_1_route_report_drc_0" -objects $obj

# Create 'methodology_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "methodology_1" ] ] ""]} {
create_dashboard_gadget -name {methodology_1} -type methodology
}
set obj [get_dashboard_gadgets [ list "methodology_1" ] ]
set_property -name "reports" -value "impl_1#impl_1_route_report_methodology_0" -objects $obj

# Create 'power_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "power_1" ] ] ""]} {
create_dashboard_gadget -name {power_1} -type power
}
set obj [get_dashboard_gadgets [ list "power_1" ] ]
set_property -name "reports" -value "impl_1#impl_1_route_report_power_0" -objects $obj

# Create 'timing_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "timing_1" ] ] ""]} {
create_dashboard_gadget -name {timing_1} -type timing
}
set obj [get_dashboard_gadgets [ list "timing_1" ] ]
set_property -name "reports" -value "impl_1#impl_1_route_report_timing_summary_0" -objects $obj

# Create 'utilization_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "utilization_1" ] ] ""]} {
create_dashboard_gadget -name {utilization_1} -type utilization
}
set obj [get_dashboard_gadgets [ list "utilization_1" ] ]
set_property -name "reports" -value "synth_1#synth_1_synth_report_utilization_0" -objects $obj
set_property -name "run.step" -value "synth_design" -objects $obj
set_property -name "run.type" -value "synthesis" -objects $obj

# Create 'utilization_2' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "utilization_2" ] ] ""]} {
create_dashboard_gadget -name {utilization_2} -type utilization
}
set obj [get_dashboard_gadgets [ list "utilization_2" ] ]
set_property -name "reports" -value "impl_1#impl_1_place_report_utilization_0" -objects $obj

move_dashboard_gadget -name {utilization_1} -row 0 -col 0
move_dashboard_gadget -name {power_1} -row 1 -col 0
move_dashboard_gadget -name {drc_1} -row 2 -col 0
move_dashboard_gadget -name {timing_1} -row 0 -col 1
move_dashboard_gadget -name {utilization_2} -row 1 -col 1
move_dashboard_gadget -name {methodology_1} -row 2 -col 1

exit

